// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How fast a moving accent moves.
 *
 * A bounded set rather than a number, and the bound is the point: this drives a colour that changes
 * under the whole interface, and an arbitrary "speed" field would let somebody configure a strobe.
 * Even `Brisk` is slow enough that a full spectrum lap takes about a minute.
 */
export type AccentSpeed = "relaxed" | "steady" | "brisk";
