// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the accent colour behaves over time.
 *
 * Every non-`Static` mode is a paid perk AND a moving element in the app shell, which this codebase
 * has repeatedly found to be expensive. Implementations must step on a timer (never per animation
 * frame), pause while the tab is hidden, and collapse to `Static` under
 * `prefers-reduced-motion: reduce`.
 */
export type AccentMode = "static" | "fade" | "gradient" | "artwork" | "chroma";
