// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ButtonSpec } from "./ButtonSpec";
import type { ImageSource } from "./ImageSource";

/**
 * What sits beside a section's text.
 */
export type Accessory = { "kind": "image", source: ImageSource, } | { "kind": "button", button: ButtonSpec, };
