// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Claims carried by a user **access token** (short-lived JWT, signed by the Hub).
 */
export type AccessClaims = { 
/**
 * Subject - the global user id.
 */
sub: string, 
/**
 * Handle at issue time (convenience; authoritative value lives in the directory).
 */
handle: string, 
/**
 * Issued-at (epoch millis).
 */
iat: bigint, 
/**
 * Expiry (epoch millis).
 */
exp: bigint, 
/**
 * Session id this token belongs to (ties the token to a device session so it can be listed /
 * revoked). Optional for backward compatibility with tokens minted before sessions existed.
 */
sid?: string | null, 
/**
 * Key id used to sign - lets the verifier select the right JWKS key during rotation.
 */
kid: string, };
