// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Read-only account overview for the settings Account/Security tabs (`GET /v1/me/account`).
 * Deliberately separate from `UserProfile`, which is hand-built in several places and returned
 * from several endpoints — widening it has a far larger blast radius than a dedicated DTO.
 */
export type AccountInfo = { 
/**
 * The account's email address. `None` for accounts created without one (e.g. OAuth-only).
 */
email?: string | null, email_verified: boolean, 
/**
 * Whether a password credential exists, so the UI offers "change" vs. "set" a password.
 */
has_password: boolean, discord_linked: boolean, totp_enabled: boolean, 
/**
 * Number of registered passkeys. **Always 0 until passkeys ship**; it exists now so the
 * Security tab's shape does not change if they ever do.
 */
passkey_count: number, };
