// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body of the library's `POST /v1/acquisition/search` — a live, scored Prowlarr search.
 */
export type AcquisitionSearch = { artist: string, album?: string | null, year?: number | null, };
