// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body of the library's `POST /v1/acquisition/grab`. Grabs a chosen candidate into a library.
 */
export type AcquisitionGrab = { guid: string, rg_mbid?: string | null, display_title?: string | null, };
