// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body of `POST /v1/manager/libraries/{id}/acquisition/report` — the library's health heartbeat.
 */
export type AcquisitionReport = { enabled: boolean, indexer_count: number, client_kind?: string | null, error?: string | null, 
/**
 * How often (days) to re-search a wanted release that hasn't been found yet, from this library's
 * `[acquisition]` config. 0 = use the Hub default.
 */
research_interval_days: number, };
