// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A hub-wide top entity, with enough to render it as more than a name.
 */
export type AdminTopEntity = { id: string, name: string, 
/**
 * Artist for an album/track, absent for an artist.
 */
subtitle?: string | null, image_hash?: string | null, plays: bigint, };
