// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What is in the catalog, and how much of the fleet is reachable.
 */
export type AdminCatalog = { artists: bigint, albums: bigint, tracks: bigint, labels: bigint, playlists: bigint, libraries: bigint, servers_online: bigint, servers_total: bigint, };
