// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminActivity } from "./AdminActivity";
import type { AdminCatalog } from "./AdminCatalog";
import type { AdminDayPoint } from "./AdminDayPoint";
import type { AdminPeople } from "./AdminPeople";
import type { AdminSignupPoint } from "./AdminSignupPoint";
import type { AdminTopEntity } from "./AdminTopEntity";

/**
 * The Overview tab's whole payload, in one request.
 */
export type AdminOverview = { people: AdminPeople, activity: AdminActivity, catalog: AdminCatalog, plays_series: Array<AdminDayPoint>, signups_series: Array<AdminSignupPoint>, top_artists: Array<AdminTopEntity>, top_albums: Array<AdminTopEntity>, top_tracks: Array<AdminTopEntity>, };
