// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlanTier } from "./PlanTier";

/**
 * `PUT /v1/admin/users/{id}/plan`: comp somebody a plan.
 *
 * Distinct from the staff and admin comps, which grant capability without a badge so a staff
 * member can still buy the badge they administer. This one reads as a real plan and earns the tier
 * badge, because giving somebody premium and withholding the thing that shows it is a half-gift.
 */
export type AdminPlanGrant = { 
/**
 * `sonic` or `super_sonic`. A grant may only ever RAISE what an account has; it never lowers a
 * tier somebody is paying for, and Free is expressed by revoking rather than by granting it.
 */
tier: PlanTier, 
/**
 * When it runs out. Absent means forever.
 */
expires_at?: bigint | null, 
/**
 * Why, for whoever reads this in a year.
 */
note?: string | null, };
