// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `PATCH /v1/admin/users/{id}/badges`.
 *
 * Three-valued per field, matching `UpdateProfile`: absent leaves it alone, `""` clears it, a value
 * sets it. Without that distinction an admin could not remove a developer title without also
 * clearing the staff role in the same request.
 */
export type AdminBadgeUpdate = { developer_title?: string | null, developer_tagline?: string | null, 
/**
 * `support` | `moderator` | `admin`, or `""` to remove the staff badge.
 */
staff_role?: string | null, 
/**
 * The languages this person has translated, or `""` to remove the translator badge. Absent
 * leaves it alone, the same three-valued convention the fields above use.
 */
translator_languages?: string | null, };
