// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How much of the catalog is still waiting on an enrichment worker.
 */
export type AdminEnrichmentBacklog = { artists_missing_art: bigint, artists_never_enriched: bigint, tracks_missing_recording: bigint, tracks_missing_isrcs: bigint, tracks_missing_lyrics: bigint, };
