// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A library this account owns, and whether its server is reachable.
 */
export type AdminUserLibrary = { id: string, name: string, track_count: bigint, online: boolean, last_heartbeat_ms?: bigint | null, };
