// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One account in the admin roster.
 */
export type AdminUserRow = { id: string, handle: string, 
/**
 * Absent for an account that has never had one — a Discord sign-in that did not share an
 * address creates exactly that, and `users.email` is nullable to match.
 */
email?: string | null, display_name: string, created_at_ms: bigint, suspended: boolean, suspended_reason?: string | null, };
