// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What they are doing.
 *
 * `dau`/`wau`/`mau` are distinct-listener counts over the trailing 1/7/30 days, read from the daily
 * rollup — never from `listening_events`, which is the partitioned fact table and the one thing an
 * admin refresh must not scan.
 */
export type AdminActivity = { plays_today: bigint, plays_7d: bigint, plays_30d: bigint, ms_played_30d: bigint, dau: bigint, wau: bigint, mau: bigint, };
