// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A hub-wide top entity, with enough to render it as more than a name.
 */
export type AdminTopEntity = { id: string, name: string, 
/**
 * Artist for an album/track, absent for an artist.
 */
subtitle?: string | null, 
/**
 * A Hub-relative path (`/v1/images/{hash}`), NOT a bare hash.
 *
 * Every other browse DTO does the same, and the client's `imageUrl()` prefixes the Hub base
 * onto whatever it is given — hand it a hash and it builds `https://hub/<hash>`, which 404s
 * silently as a broken image rather than as an error.
 */
image_url?: string | null, plays: bigint, };
