// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminEnrichmentBacklog } from "./AdminEnrichmentBacklog";
import type { AdminRollupStat } from "./AdminRollupStat";
import type { AdminTableSize } from "./AdminTableSize";

/**
 * Operator health, everything an admin would otherwise reach for psql to answer.
 */
export type AdminSystemHealth = { version: string, migrations_applied: bigint, db_bytes: bigint, listening_events_partitions: bigint, rollups: Array<AdminRollupStat>, biggest_tables: Array<AdminTableSize>, enrichment: AdminEnrichmentBacklog, };
