// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One day of hub-wide activity.
 *
 * `listeners` is what separates a busy day from one heavy listener, and it cannot be derived from
 * `plays` — which is exactly why it is a column here rather than something the client computes.
 */
export type AdminDayPoint = { 
/**
 * Local calendar day, `YYYY-MM-DD`. A DATE read as text: this crate's sqlx has no chrono.
 */
day: string, plays: bigint, listeners: bigint, ms_played: bigint, };
