// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminSession } from "./AdminSession";
import type { AdminUserDetail } from "./AdminUserDetail";
import type { AdminUserLibrary } from "./AdminUserLibrary";
import type { AuditEntry } from "./AuditEntry";
import type { ProfileBadge } from "./ProfileBadge";

/**
 * Everything the user-detail page renders, in one request.
 */
export type AdminUserProfile = { user: AdminUserDetail, 
/**
 * Total listening time, milliseconds. From the daily rollup, never the fact table.
 */
ms_played: bigint, 
/**
 * Distinct days with any listening at all — a better read of "is this account used" than a
 * play count, which one long weekend can inflate.
 */
active_days: bigint, first_play_ms?: bigint | null, last_play_ms?: bigint | null, playlists: bigint, sessions: Array<AdminSession>, libraries: Array<AdminUserLibrary>, 
/**
 * This account's recent history as a TARGET of admin action, not as an actor.
 */
recent_audit: Array<AuditEntry>, 
/**
 * Every badge this account carries, assignable or not.
 *
 * The full list rather than just the two an admin can change, because the derived ones are
 * context an admin needs: whether someone is already a paying supporter changes whether comping
 * them a staff role is generous or redundant. The editor renders the assignable pair and shows
 * the rest as read-only.
 */
badges: Array<ProfileBadge>, };
