// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One account in the admin roster.
 */
export type AdminUserRow = { id: string, handle: string, email: string, display_name: string, created_at_ms: bigint, suspended: boolean, suspended_reason?: string | null, };
