// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminUserDetail } from "./AdminUserDetail";

/**
 * A page of the roster, plus the total the filters match.
 *
 * Offset paging here, not keyset: the roster is small, sortable by any column, and an admin
 * genuinely wants "page 3 of 7" — the properties that made keyset right for the audit log are all
 * absent.
 */
export type AdminUserPage = { rows: Array<AdminUserDetail>, total: bigint, };
