// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One background rollup and how far behind it is.
 */
export type AdminRollupStat = { name: string, 
/**
 * How far behind the newest event this rollup has processed, in seconds.
 */
lag_seconds: bigint, last_event_ms: bigint, };
