// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One sign-in session.
 */
export type AdminSession = { session_id: string, 
/**
 * Raw UA string. Rendered as-is: parsing it into "Chrome on macOS" is a guess, and an operator
 * chasing a suspicious session wants the actual header.
 */
user_agent?: string | null, created_at_ms: bigint, last_used_at_ms: bigint, 
/**
 * A long-lived token — a paired device rather than a browser sign-in.
 */
long_lived: boolean, };
