// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlanTier } from "./PlanTier";

/**
 * A live comp, as the admin user page shows it.
 */
export type AdminPlanGrantView = { tier: PlanTier, expires_at?: bigint | null, note?: string | null, granted_at: bigint, };
