// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A count of download jobs in one status.
 */
export type AdminQueueStat = { status: string, count: bigint, };
