// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who is on the server.
 */
export type AdminPeople = { total: bigint, new_7d: bigint, new_30d: bigint, suspended: bigint, admins: bigint, verified: bigint, with_totp: bigint, };
