// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One pending field-suggestion in the admin review queue, with the entity's current value so the
 * admin can compare before approving.
 */
export type AdminSuggestion = { id: string, reporter_handle: string, entity_type: string, entity_id: string, entity_name: string, field: string, value_text?: string | null, value_image_hash?: string | null, 
/**
 * The entity's current text value for this field (name/bio/genres), for before/after comparison.
 */
current_text?: string | null, 
/**
 * The entity's current image/banner hash for this field.
 */
current_image_hash?: string | null, note?: string | null, created_at_ms: bigint, };
