// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtRecording } from "./ExtRecording";

/**
 * One edition of an album (Standard, Deluxe, Expanded, Remaster, …) with its own tracklist and
 * owned/missing breakdown.
 */
export type AlbumEdition = { 
/**
 * The representative release MBID for this edition.
 */
release_mbid: string, 
/**
 * Display label, e.g. "Standard", "Special edition", "2020 remaster".
 */
label: string, 
/**
 * True when this edition is a remaster (same songs, different master), shown independently.
 */
is_remaster: boolean, cover_url?: string | null, 
/**
 * Total tracks in this edition.
 */
total: number, 
/**
 * How many of them the user owns.
 */
owned_count: number, 
/**
 * This edition's tracklist in order, each flagged `owned`.
 */
tracks: Array<ExtRecording>, };
