// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The Hub's canonical primary artist for one synced album, so the library can organize files on disk
 * under the same name the Hub shows (e.g. a collab tagged "Wiz Khalifa & MGK" resolves to "mgk", and
 * "Machine Gun Kelly"/"MGK" fold to "mgk"). Keyed by the album's normalized title + the album-artist
 * name the library sent, which together identify the library's album row.
 */
export type AlbumArtistResolution = { album_normalized: string, 
/**
 * The album-artist string the library sent (so it can match its own album row).
 */
album_artist: string, 
/**
 * The Hub's canonical primary-artist name for that album.
 */
canonical_artist: string, };
