// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlbumEdition } from "./AlbumEdition";

/**
 * Every edition of one album (release-group), each with its own tracklist + owned/missing breakdown.
 * This is the Manager's album view. Works for an album the user owns (to show which tracks/editions are
 * missing) and for one they don't own at all (everything missing).
 */
export type AlbumTrackCoverage = { 
/**
 * The release-group MBID this breakdown is for.
 */
rg_mbid: string, title: string, cover_url?: string | null, 
/**
 * The album artist's MusicBrainz id, for linking.
 */
artist_mbid?: string | null, 
/**
 * The album artist's display name, for the breadcrumb trail and linking back to the artist.
 */
artist_name?: string | null, 
/**
 * The album artist's image, for the breadcrumb avatar.
 */
artist_image_url?: string | null, 
/**
 * The album's editions, in display order (Standard first).
 */
editions: Array<AlbumEdition>, 
/**
 * True while the recording listing is still being fetched.
 */
refreshing: boolean, };
