// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AlbumOverrideView = { title?: string | null, cover_url?: string | null, year?: number | null, label?: string | null, album_type?: string | null, genres?: Array<string> | null, override_main: boolean, };
