// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An album grouping.
 */
export type Album = { id: string, title: string, artist: string, year: number | null, track_count: number, cover_url?: string | null, };
