// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreditGroup } from "./CreditGroup";

/**
 * Response of `GET /v1/albums/{id}/credits` — the union across the album's tracks.
 *
 * An aggregate rather than a per-track breakdown: an album's producer is nearly always the same
 * name repeated down every track, and printing it forty times is not liner notes, it is a wall.
 * The per-track view is one request away on the track itself.
 */
export type AlbumCredits = { album_id: string, groups: Array<CreditGroup>, 
/**
 * How many of the album's tracks contributed at least one credit, so the panel can say
 * "from 9 of 12 tracks" instead of implying the album is fully documented when it is not.
 */
tracks_with_credits: number, track_count: number, };
