// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BrowseTrack } from "./BrowseTrack";

/**
 * Full album page payload.
 */
export type AlbumDetail = { id: string, 
/**
 * MusicBrainz release-group id, when known. Mirrors `BrowseAlbum::mbid`, so a menu can link
 * straight to this release in the Manager rather than running a name search.
 */
mbid?: string | null, title: string, artist: string, artist_id?: string | null, 
/**
 * The primary artist's image (for the breadcrumb / header artist chip). Framing-aware.
 */
artist_image_url?: string | null, year: number | null, release_date?: string | null, 
/**
 * Canonical label display name (from the linked label entity, or a per-library override).
 */
label?: string | null, 
/**
 * Canonical label id (for linking to the label page). None when unlabeled / override-only.
 */
label_id?: string | null, album_type?: string | null, 
/**
 * Secondary release-group types (EP / Single / Compilation / Live / Remix / …).
 */
secondary_types: Array<string>, genres: Array<string>, cover_url?: string | null, 
/**
 * Total plays across all tracks on this album.
 */
plays: number, tracks: Array<BrowseTrack>, };
