// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtistLabel } from "./ArtistLabel";
import type { ArtistLink } from "./ArtistLink";
import type { ArtistRelation } from "./ArtistRelation";
import type { BrowseAlbum } from "./BrowseAlbum";
import type { BrowseTrack } from "./BrowseTrack";

/**
 * Full artist page payload.
 */
export type ArtistDetail = { id: string, 
/**
 * MusicBrainz id, when known. Lets a menu link straight to the artist's Manager discography
 * page instead of dropping the user into a name search. Mirrors `BrowseArtist::mbid`.
 */
mbid?: string | null, name: string, image_url?: string | null, banner_url?: string | null, 
/**
 * Intrinsic pixel width of `banner_url`'s image, when the Hub knows it.
 *
 * The banner is rendered edge-to-edge with a `srcSet`, and a `Nw` descriptor is a PROMISE about
 * the candidate's real width — the browser picks on that number without ever measuring the
 * file. Banner art comes from fanart.tv at whatever size the uploader chose, so a hard-coded
 * descriptor is a guess, and guessing high makes the browser choose a small file for a wide
 * slot and upscale it. Absent means "unknown": emit no `srcSet` rather than an invented one.
 */
banner_width?: number | null, bio?: string | null, genres: Array<string>, 
/**
 * Distinct listeners across the Hub in the last ~30 days.
 */
monthly_listeners: number, 
/**
 * Where the artist is from (associated area / country region name).
 */
area?: string | null, 
/**
 * Formation place / birthplace.
 */
begin_area?: string | null, 
/**
 * Career/life start, raw MB partial date (`YYYY` | `YYYY-MM` | `YYYY-MM-DD`).
 */
begin_date?: string | null, 
/**
 * Career/life end (disbanded / deceased), if any.
 */
end_date?: string | null, 
/**
 * True when the artist's life-span has ended (group disbanded / person deceased).
 */
ended?: boolean | null, 
/**
 * MB type: `"Person"`, `"Group"`, `"Orchestra"`, …
 */
artist_type?: string | null, 
/**
 * Linked artists such as aliases, side-projects, or bands (see [`ArtistRelation`]).
 */
related: Array<ArtistRelation>, 
/**
 * Labels this artist has released on, with the year span (derived from their albums).
 */
labels: Array<ArtistLabel>, 
/**
 * External links (official site, streaming, social) from MusicBrainz, curated to the platforms
 * worth surfacing. Rendered as icon links on the artist page.
 */
links: Array<ArtistLink>, albums: Array<BrowseAlbum>, top_tracks: Array<BrowseTrack>, 
/**
 * Owned live material for this artist (live-version album tracks + scattered "(Live)" bonus
 * variants), so the client can offer the dynamic Live album even when no live album exists.
 */
live_track_count: number, };
