// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ArtistOverrideView = { name?: string | null, image_url?: string | null, banner_url?: string | null, bio?: string | null, genres?: Array<string> | null, override_main: boolean, };
