// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One external link for an artist. `kind` is a stable platform slug the UI maps to an icon:
 * `website`, `spotify`, `apple_music`, `youtube`, `youtube_music`, `soundcloud`, `bandcamp`,
 * `tidal`, `deezer`, `instagram`, `twitter`, `tiktok`, `facebook`, `wikipedia`.
 */
export type ArtistLink = { kind: string, url: string, };
