// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `POST /v1/catalog/artists:art`: artists by MusicBrainz id, else by normalized name (the same
 * normalization both sides use for `name_normalized`).
 */
export type ArtistArtRequest = { mbids: Array<string>, names_normalized: Array<string>, };
