// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A reference to one artist (for rendering a track's per-artist links).
 */
export type ArtistRef = { id: string, name: string, };
