// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ArtistOverrideInput = { name?: string | null, 
/**
 * Hash of an image uploaded via `POST /v1/images`.
 */
image_hash?: string | null, banner_hash?: string | null, bio?: string | null, genres?: Array<string> | null, override_main: boolean, };
