// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An artist grouping.
 */
export type Artist = { id: string, name: string, album_count: number, };
