// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A label an artist has released on, with the span of years (for the artist-page label history).
 */
export type ArtistLabel = { id: string, name: string, 
/**
 * Earliest / latest release year on this label (either may be None if no dates are known).
 */
first_year?: number | null, last_year?: number | null, album_count: number, };
