// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An artist's page id and pictures. URLs are relative to the Hub, like every image URL it serves.
 */
export type ArtistArt = { artist_id: string, name: string, name_normalized: string, mbid?: string | null, image_url?: string | null, banner_url?: string | null, };
