// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One artist linked to another (an alias / side-project / band membership). Rendered as a
 * clickable chip on the artist page; each row is a real, independent artist (never a merge).
 */
export type ArtistRelation = { id: string, name: string, image_url?: string | null, 
/**
 * Coarse bucket the UI groups by: `"alias"` (also-known-as / pseudonym), `"member"` (band
 * membership, either direction), or `"related"` (collaboration / other).
 */
relation: string, };
