// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BrowseAlbum } from "./BrowseAlbum";
import type { ExtReleaseGroup } from "./ExtReleaseGroup";

/**
 * Owned-vs-missing breakdown for one artist the user (partially) owns.
 */
export type ArtistCoverage = { 
/**
 * The owned-catalog artist id (for navigation).
 */
artist_id: string, name: string, 
/**
 * The artist's MusicBrainz id, if known (needed to diff the discography).
 */
artist_mbid?: string | null, 
/**
 * Albums the user owns (from their libraries).
 */
owned: Array<BrowseAlbum>, 
/**
 * Release-groups in the discography the user does NOT own.
 */
missing: Array<ExtReleaseGroup>, 
/**
 * Album-level coverage for this artist (0..100).
 */
coverage_pct: number, 
/**
 * True when the discography is still being fetched (missing list is provisional). The client
 * should refetch on the next realtime catalog nudge.
 */
refreshing: boolean, };
