// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One artwork candidate for the metadata-editor art picker (from fanart.tv / Cover Art Archive).
 */
export type ArtOption = { 
/**
 * Direct image URL at the provider.
 */
url: string, 
/**
 * What the image is: `thumb` | `banner` | `background` | `logo` (artist) or `cover` (album).
 */
kind: string, };
