// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtOption } from "./ArtOption";

/**
 * Available artwork for an artist or album. These are the choices shown in the art picker.
 */
export type ArtOptions = { options: Array<ArtOption>, };
