// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ListeningEvent } from "./ListeningEvent";

/**
 * One play, for one listener.
 */
export type AttributedEvent = { user_id: string, event: ListeningEvent, };
