// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttributedEvent } from "./AttributedEvent";

/**
 * `POST /v1/scrobbles:ingest-attributed`: plays the bot heard people listen to. The Hub re-checks
 * every `user_id` against the trust rule; the batch's `client_type` is forced to Discord.
 */
export type AttributedScrobbleBatch = { events: Array<AttributedEvent>, };
