// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An account that appears as an actor in the log.
 */
export type AuditActor = { id: string, handle: string, };
