// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry in the append-only privileged-action log.
 *
 * `target_type` and `target_label` are what make an entry legible. A bare `target_id` is a UUID
 * with no way to resolve it — worse, `delete_user` destroys the row it points at, so after the fact
 * there is nothing left to resolve it *against*. The label is therefore captured at write time and
 * denormalized here on purpose; it is a record of what the target was called when the thing
 * happened, not a live lookup.
 */
export type AuditEntry = { 
/**
 * BIGSERIAL, strictly monotonic — which is what keyset pagination pages on.
 */
id: bigint, actor_id?: string | null, actor_handle?: string | null, action: string, 
/**
 * `admin` | `moderation` | `catalog` | `auth` | `system`. Coarse enough to filter by.
 */
category: string, 
/**
 * `user` | `artist` | `album` | `track` | `label` | `report` | `suggestion`, or absent.
 */
target_type?: string | null, target_id?: string | null, target_label?: string | null, detail?: string | null, 
/**
 * The entity's relevant fields before and after the change, narrowed to what actually moved.
 */
before?: { [key in string]: string | null } | null, after?: { [key in string]: string | null } | null, 
/**
 * True when `target_type`/`target_label` were INFERRED by the migration rather than recorded.
 *
 * Surfaced rather than hidden: a backfilled label is the target's name *today*, not its name
 * when the action happened, and for a deleted target there is no label at all. An operator
 * reading an old entry needs to know which kind they are looking at.
 */
backfilled: boolean, created_at_ms: bigint, };
