// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuditEntry } from "./AuditEntry";

/**
 * A page of the audit log, plus the cursor for the page after it.
 *
 * Keyset, not offset: the log is append-only and unbounded, so an offset page shifts under the
 * reader every time anything privileged happens while they are looking at it.
 */
export type AuditPage = { rows: Array<AuditEntry>, 
/**
 * Pass back as `before_id` for the next page. `None` means this was the last one.
 */
next_before_id?: bigint | null, };
