// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Audio stream characteristics, captured at scan time.
 */
export type AudioProperties = { 
/**
 * Container/codec, e.g. `flac`, `alac`, `wav`, `aac`, `mp3`, `eac3`.
 */
codec: string, sample_rate_hz: number, bit_depth: number, channels: number, 
/**
 * Whether this is a lossless source.
 */
lossless: boolean, 
/**
 * Spatial/Atmos source, flagged `passthrough_only` and never transcoded.
 */
spatial: boolean, 
/**
 * ReplayGain 2.0 track gain in dB (reference −18 LUFS), computed by the loudness pass. `None`
 * until analyzed (or if ffmpeg/EBU R128 analysis is unavailable). The client applies it as a
 * preamp when "Normalize volume" is on.
 */
gain_db?: number | null, 
/**
 * Linear true-peak amplitude (≈0..1+), paired with `gain_db` to prevent clipping when applying
 * the gain (the applied gain is capped at `1/peak`).
 */
peak?: number | null, };
