// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuditActor } from "./AuditActor";

/**
 * The distinct values actually present in the log, for populating the filter dropdowns.
 *
 * Derived from the data rather than from a hard-coded list, so an action added on the server shows
 * up in the filter without a matching client release — and one that has never fired does not
 * offer an empty filter.
 */
export type AuditFacets = { actions: Array<string>, categories: Array<string>, actors: Array<AuditActor>, };
