// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who may see one profile surface. Used for the per-surface visibility knobs in
 * [`UserSettings`].
 *
 * This is shape-identical to [`ScrobblePrivacy`] on purpose — see the note there for why the two
 * must not be merged.
 */
export type Audience = "public" | "friends" | "private";
