// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TokenPair } from "./TokenPair";
import type { UserProfile } from "./UserProfile";

/**
 * Response from register/login: the profile plus a fresh token pair.
 */
export type AuthResponse = { user: UserProfile, tokens: TokenPair, };
