// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One archive on disk, as listed. Nothing here requires decrypting it.
 */
export type BackupFile = { 
/**
 * File name, which is also the id used to verify or restore it. Never a path: the directory is
 * server-side configuration and a client that could name one could name `/etc/passwd`.
 */
name: string, size_bytes: bigint, 
/**
 * From the filename stamp when it parses, falling back to the file's mtime.
 */
created_at_ms: bigint, 
/**
 * `.age` suffix. An unencrypted archive is a finding, not a feature: it means every credential
 * on the instance is sitting in a file with only filesystem permissions in front of it.
 */
encrypted: boolean, };
