// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackupFile } from "./BackupFile";
import type { LedgerStatus } from "./LedgerStatus";
import type { LocalStatus } from "./LocalStatus";
import type { RemoteStatus } from "./RemoteStatus";

/**
 * The backups page in one response.
 */
export type BackupIndex = { 
/**
 * Newest first.
 */
files: Array<BackupFile>, 
/**
 * Where the Hub is looking, so "no backups" can be told apart from "looking in the wrong place".
 * That distinction is the difference between a missing cron job and a missing volume mount.
 */
directory: string, 
/**
 * `None` when no directory is configured at all, which is its own answer.
 */
local?: LocalStatus | null, 
/**
 * `None` when no directory is configured at all, which is its own answer.
 */
ledger?: LedgerStatus | null, 
/**
 * `None` when no read credentials are configured, so the list is the server's copies alone.
 * Distinct from a configured remote that returned nothing, which is [`RemoteStatus::reachable`].
 */
remote?: RemoteStatus | null, };
