// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What inspecting an archive found. Produced without writing anything.
 */
export type BackupVerdict = { name: string, 
/**
 * The archive decrypted, unpacked, and carries pg_dump's completion marker.
 */
intact: boolean, 
/**
 * Why not, when `intact` is false. A wrong key and a truncated file are different problems.
 */
problem?: string | null, 
/**
 * Uncompressed size of the SQL, so a suspiciously small archive is visible before it is applied.
 */
sql_bytes: bigint, 
/**
 * **The number that decides whether to proceed.** Accounts named by the CURRENT erasure ledger
 * that this archive would bring back. `erasures::replay` re-erases them, so this is not a
 * blocker — but restoring without knowing it is how a GDPR breach happens quietly.
 */
would_resurrect: bigint, 
/**
 * Ids of those accounts, capped for display. Full count is `would_resurrect`.
 */
sample: Array<string>, };
