// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One archive on disk, as listed. Nothing here requires decrypting it.
 */
export type BackupFile = { 
/**
 * File name, which is also the id used to verify or restore it. Never a path: the directory is
 * server-side configuration and a client that could name one could name `/etc/passwd`.
 */
name: string, size_bytes: bigint, 
/**
 * From the filename stamp when it parses, falling back to the file's mtime.
 */
created_at_ms: bigint, 
/**
 * `.age` suffix. An unencrypted archive is a finding, not a feature: it means every credential
 * on the instance is sitting in a file with only filesystem permissions in front of it.
 */
encrypted: boolean, 
/**
 * Present on the Hub's disk, so it can be verified and restored from here.
 */
local: boolean, 
/**
 * Present in object storage. **`remote && !local` is the row that matters**: it is the copy
 * that survived losing the machine, and it is invisible to a listing that reads only one side.
 */
remote: boolean, 
/**
 * Size in object storage, when it is there. Separate from `size_bytes` rather than merged so a
 * disagreement between the two copies is visible instead of averaged away — same name, two
 * different lengths, means one of them is a truncated upload.
 */
remote_bytes?: bigint | null, };
