// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BadgeCountPoint } from "./BadgeCountPoint";

/**
 * One badge in the instance's badge directory: what it is, who has it, and whether it is still
 * possible to get.
 *
 * Deliberately keyed by the same `kind` strings [`ProfileBadge`] tags itself with, so the directory
 * and a badge on a profile are provably the same set — a badge that exists but is missing from the
 * directory would be the failure nobody notices.
 */
export type BadgeCatalogEntry = { 
/**
 * `developer` | `staff` | `early_bird` | `early_supporter` | `sonic` | `super_sonic`.
 */
kind: string, 
/**
 * How many accounts currently carry it.
 */
holders: number, 
/**
 * Whether a new account could still earn it today.
 *
 * False for the early-bird badge once its cutoff has passed, and for the early-supporter badge
 * once all hundred ranks are taken. The tier badges are always obtainable; the granted ones
 * (developer, staff) are obtainable only in the sense that an admin may grant them, which is
 * reported as false because it is not something a reader can go and do.
 */
obtainable: boolean, 
/**
 * When the badge stops being obtainable, if that is a date. Only the early-bird badge has one.
 */
available_until?: bigint | null, 
/**
 * How many of a capped badge remain. Only the early-supporter badge is capped.
 */
remaining?: number | null, 
/**
 * Cumulative holders over time, oldest first — one point per day on which the count changed.
 *
 * Empty where the history is not recorded rather than estimated. A tier badge only knows when
 * its holder's CURRENT streak began, so a subscriber count for last March cannot be recovered
 * and is not invented; the client says so instead of drawing a line.
 */
history: Array<BadgeCountPoint>, };
