// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One point on a badge's holders-over-time line.
 */
export type BadgeCountPoint = { 
/**
 * `YYYY-MM-DD`, in UTC.
 */
day: string, 
/**
 * Total holders as of the end of that day.
 */
holders: number, };
