// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BillingInterval } from "./BillingInterval";
import type { BillingStatus } from "./BillingStatus";
import type { Entitlements } from "./Entitlements";

/**
 * `GET /v1/billing/me`. The billing view of the account, beside its entitlements.
 */
export type BillingMe = { entitlements: Entitlements, status: BillingStatus, interval?: BillingInterval | null, 
/**
 * When the current paid period ends: the renewal date, or the date access stops if cancelled.
 */
current_period_end?: bigint | null, cancel_at_period_end: boolean, 
/**
 * Whether a billing-portal link can be minted for this account.
 */
has_customer: boolean, 
/**
 * A checkout started but not yet confirmed by a webhook, so the plan page can say "activating"
 * after a reload rather than looking like the payment did nothing.
 */
pending_checkout?: bigint | null, };
