// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The lifecycle state of a subscription, as far as the account is concerned.
 *
 * `Canceled` is NOT the same as `Expired`: a canceled subscription keeps its entitlements until
 * the period already paid for runs out, which is the difference between "I turned off renewal" and
 * "I no longer have this".
 */
export type BillingStatus = "none" | "active" | "trialing" | "past_due" | "canceled" | "paused" | "expired";
