// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `POST /v1/lyrics:bot`: lyrics for one of a server's own tracks, for its Discord bot, by the
 * library's own track id. Answered with the same [`Lyrics`](crate::lyrics::Lyrics) a person gets.
 */
export type BotLyricsRequest = { 
/**
 * The Hub's id for the library (the one catalog sync uses).
 */
library_id: string, track_ref: string, };
