// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtistRef } from "./ArtistRef";

/**
 * A track row as shown in a list. `library_id` tells the player which library to stream from.
 */
export type BrowseTrack = { id: string, title: string, 
/**
 * Display string of all credited artists (e.g. `"Drake feat. Rihanna"`).
 */
artist: string, 
/**
 * Primary artist id (album attribution / "main artist" navigation).
 */
artist_id?: string | null, 
/**
 * All credited artists, ordered (primary first), for per-artist links. May be empty for
 * legacy rows synced before multi-artist support.
 */
artists: Array<ArtistRef>, album?: string | null, album_id?: string | null, track_no: number | null, disc_no: number | null, 
/**
 * Edition qualifier ("Deluxe", …) when this track is from a deluxe/special edition folded into
 * the base album; `None` for the standard edition. Lets the album view badge the extra tracks.
 */
edition?: string | null, 
/**
 * Content advisory: `"explicit"` or `"clean"` (from the file's iTunes/ID3 rating tag), `None`
 * when unrated. Drives the EXPLICIT badge.
 */
advisory?: string | null, duration_ms: number, 
/**
 * Total times this track has been played (across the Hub).
 */
plays: number, cover_url?: string | null, 
/**
 * The library this playable track lives in (for grant + streaming).
 */
library_id: string, 
/**
 * The library's own track id, used to build the stream URL.
 */
track_ref: string, content_hash: string, 
/**
 * When the track was added to the playlist / liked (epoch ms). None outside those contexts.
 */
added_at?: bigint | null, };
