// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An album as shown in a grid.
 */
export type BrowseAlbum = { id: string, title: string, artist: string, artist_id?: string | null, year: number | null, cover_url?: string | null, track_count: number, 
/**
 * MusicBrainz release-group MBID, when known. Lets the Manager link an owned album to its
 * coverage/tracklist view (which is keyed by release-group).
 */
mbid?: string | null, 
/**
 * First-release date (`YYYY-MM-DD`), when known. Used for precise newest-first ordering and
 * labels in the discography (finer than `year`).
 */
release_date?: string | null, 
/**
 * Primary release type (`Album`/`EP`/`Single`/`Compilation`/…), when known. Drives the
 * discography type badges.
 */
album_type?: string | null, 
/**
 * Version tag: absent for the studio release, "instrumental" / "live" for a version release, so
 * browsing can shelve them separately and Manager Discover can badge them.
 */
version_type?: string | null, 
/**
 * True when this album is in the list only because the artist is a FEATURED credit on one of its
 * tracks (not the album's primary artist) — lets the discography mark "appears on" entries.
 */
appears_on: boolean, };
