// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An artist as shown in a grid.
 */
export type BrowseArtist = { id: string, 
/**
 * MusicBrainz id, when known. Lets the Manager link an owned artist to its browse-all page.
 */
mbid?: string | null, name: string, image_url?: string | null, album_count: number, track_count: number, };
