// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Grain the over-time series is bucketed at, so the client can label its x-axis correctly.
 */
export type BucketGranularity = "hour" | "day" | "week" | "month" | "year";
