// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ControlButton } from "./ControlButton";

/**
 * A button: one of the bot's controls, or a link with your own label.
 */
export type ButtonSpec = { "kind": "control", control: ControlButton, } | { "kind": "link", label: string, url: string, };
