// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One scored candidate the library found (reported for interactive selection).
 */
export type CandidateInput = { guid: string, title: string, indexer?: string | null, quality_label?: string | null, score?: number | null, size_bytes?: bigint | null, seeders?: number | null, leechers?: number | null, 
/**
 * The release's actual download source, persisted with the candidate so a later user pick
 * grabs it directly instead of re-resolving the guid with a live (ephemeral) Prowlarr search.
 */
download_url?: string | null, magnet_url?: string | null, info_hash?: string | null, };
