// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a capability token authorizes the holder to do.
 */
export type CapabilityAction = "stream_read" | "relay_pull" | "manage_acquisition" | "recover_management";
