// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapabilityAction } from "./CapabilityAction";
import type { PermissionLevel } from "./PermissionLevel";
import type { ResourceRef } from "./ResourceRef";

/**
 * Claims inside a **capability token** - the linchpin of the data-plane security model.
 *
 * Minted by the Hub only after verifying friendship + share permissions, then validated
 * **offline** by the target library against the Hub JWKS.
 */
export type CapabilityClaims = { 
/**
 * Subject - the user (or, for relay, the requesting library's owner) being authorized.
 */
sub: string, 
/**
 * Audience - the `server_id` of the library expected to honor this token.
 */
aud: string, 
/**
 * Library the resource lives in.
 */
library_id: string, 
/**
 * What may be accessed.
 */
resource: ResourceRef, 
/**
 * What may be done with it.
 */
action: CapabilityAction, 
/**
 * Permission level granted to the subject for this library (owner → Download, shared → per-share).
 */
permission_level: PermissionLevel, 
/**
 * Room context, set for relay tokens so the DJ's library can scope the grant.
 */
room_id?: string | null, 
/**
 * Unique token id - enables revocation lists and replay detection.
 */
jti: string, iat: bigint, exp: bigint, kid: string, };
