// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncTrack } from "./SyncTrack";

/**
 * Body of `POST /v1/catalog/sync` (authenticated `Authorization: Library {server_api_key}`).
 */
export type CatalogSyncRequest = { 
/**
 * The Hub-side library UUID this catalog belongs to.
 */
library_id: string, tracks: Array<SyncTrack>, };
