// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlbumArtistResolution } from "./AlbumArtistResolution";

/**
 * Response to a catalog sync: how many tracks were accepted and which referenced cover hashes the
 * Hub still needs the bytes for (upload via `PUT /v1/catalog/covers/{hash}`).
 */
export type CatalogSyncResponse = { accepted: number, missing_covers: Array<string>, 
/**
 * The Hub's canonical album-artist per album in this batch, so the library can file albums under
 * the same name (and relocate when it changes). Empty from older Hubs.
 */
canonical_album_artists: Array<AlbumArtistResolution>, };
