// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body of `POST /v1/catalog/prune` (server-authenticated). The authoritative set of track refs the
 * library still has; the Hub drops memberships for any of this library's tracks not in the set, so
 * files deleted on the library side disappear from browsing.
 */
export type CatalogPruneRequest = { 
/**
 * The Hub-side library UUID this prune applies to.
 */
library_id: string, 
/**
 * Every `track_ref` the library currently has for this library.
 */
track_refs: Array<string>, };
