// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body of the password-change endpoint.
 */
export type ChangePasswordRequest = { current_password: string, new_password: string, 
/**
 * Sign every other device out after the change. Defaults to true — the safe reading of a
 * password change is that the old one may be compromised.
 */
revoke_other_sessions: boolean, };
