// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BillingInterval } from "./BillingInterval";
import type { PlanTier } from "./PlanTier";

/**
 * `POST /v1/billing/change`: move an existing subscription to another tier or interval.
 */
export type ChangePlanRequest = { tier: PlanTier, interval: BillingInterval, };
