// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One ranked catalog entry in a current-versus-previous-window chart.
 */
export type ChartEntry = { id: string, name: string, subtitle?: string | null, image_url?: string | null, plays: number, ms_played: bigint, rank: number, prev_rank?: number | null, global_plays?: bigint | null, };
