// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChartEntry } from "./ChartEntry";
import type { EntityKind } from "./EntityKind";
import type { Period } from "./Period";

/**
 * One page of a listener's full ranked library. Offset-paged rather than keyset: the ranking is
 * dense and recomputed per window, so there is no stable cursor to page from, and a reader jumping
 * to "page 7" expects ranks 121–140 rather than wherever a cursor happened to land.
 */
export type ChartPage = { kind: EntityKind, period: Period, window_start: bigint, window_end: bigint, 
/**
 * Distinct entities of this kind the listener played in the window — the denominator behind
 * "#7 of 412", and what tells the client whether another page exists.
 */
total: number, offset: number, entries: Array<ChartEntry>, };
