// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BillingInterval } from "./BillingInterval";
import type { PlanTier } from "./PlanTier";

/**
 * `POST /v1/billing/checkout`.
 */
export type CheckoutRequest = { tier: PlanTier, interval: BillingInterval, };
