// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CheckoutResponse = { 
/**
 * Send the browser here. Hosted by the payment provider; card details never reach the Hub.
 */
checkout_url: string, 
/**
 * Our idempotency key, echoed back on the return URL so the page can poll for activation.
 */
request_id: string, };
