// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DownloadQualityProfile } from "./DownloadQualityProfile";

/**
 * A claimed job with everything the library needs to execute it WITHOUT its own MusicBrainz access:
 * the resolved search hints (artist/album/year) and the quality profile to score against.
 */
export type ClaimedJob = { job_id: string, library_id: string, kind: string, artist_mbid?: string | null, rg_mbid?: string | null, 
/**
 * The specific release (edition) this job targets, when the user picked one (e.g. the Deluxe
 * edition). None = the whole release-group. Scopes `expected_titles` to just this edition.
 */
release_mbid?: string | null, 
/**
 * The edition label ("Deluxe", "2009 Remaster", …) for `release_mbid`. The library appends it to
 * the Prowlarr query to steer results toward that exact edition (falling back to the plain query).
 */
edition_label?: string | null, recording_mbid?: string | null, display_title?: string | null, 
/**
 * Pre-chosen release (set when the user picked a candidate for an interactive job). The library
 * grabs this directly and skips the search/score step.
 */
chosen_guid?: string | null, 
/**
 * The chosen candidate's release title (as it appeared in the pick list).
 */
chosen_title?: string | null, 
/**
 * The chosen candidate's stored source, captured at candidate time. When present the library
 * grabs it directly — no live Prowlarr re-search, so a pick never expires. Absent on legacy
 * picks made before sources were persisted (the library falls back to re-searching the guid).
 */
chosen_download_url?: string | null, chosen_magnet_url?: string | null, chosen_info_hash?: string | null, chosen_indexer?: string | null, chosen_size_bytes?: bigint | null, chosen_seeders?: number | null, interactive: boolean, 
/**
 * A quality-upgrade job (queued by the library's upgrade sweep): the library must only grab a
 * release STRICTLY better than the owned copy (v1: lossless, since sweeps propose all-lossy
 * albums), and must go quietly to `no_results` instead of asking when unsure — upgrades are
 * unattended.
 */
upgrade: boolean, quality_profile?: DownloadQualityProfile | null, artist_name?: string | null, 
/**
 * The artist's name AS CREDITED IN THE RELEASE ERA (resolved Hub-side from the artist's
 * date-ranged MusicBrainz aliases against the release year), e.g. "Machine Gun Kelly" for a
 * 2019 album even though the artist is now "mgk". The library searches this FIRST (trackers
 * indexed the release under the era name), falling back to `artist_name` (the current name).
 */
era_artist_name?: string | null, album_title?: string | null, year?: number | null, 
/**
 * The album's expected track titles (from the Hub's MusicBrainz cache), so the library can verify
 * the downloaded content actually IS this album before importing, and fail a mislabelled grab.
 * Empty when the Hub has no cached tracklist (verification is then skipped).
 */
expected_titles?: Array<string>, 
/**
 * For a single-TRACK download (`kind="track"`): the exact title(s) to import. The library then
 * imports ONLY the matching file(s) from the grabbed release — not the whole album — and rejects a
 * release that doesn't contain the track (so downloading one bonus track can't dump a whole,
 * possibly-wrong album into the library). Empty for album/discography jobs (import everything).
 */
wanted_titles?: Array<string>, };
