// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrackFingerprint } from "./TrackFingerprint";

/**
 * Messages a client sends over the room WebSocket.
 */
export type ClientMessage = { "type": "join", room_id: string, } | { "type": "leave" } | { "type": "play" } | { "type": "pause" } | { "type": "seek", position_ms: number, } | { "type": "next" } | { "type": "enqueue", fingerprint: TrackFingerprint, } | { "type": "vote", queue_id: string, up: boolean, } | { "type": "chat", body: string, } | { "type": "ping", client_time: bigint, };
