// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The originating client type.
 */
export type ClientType = "web" | "desktop" | "mobile";
