// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Listening intensity by local weekday and hour.
 */
export type ClockGrid = { 
/**
 * IANA timezone used to place events into local calendar cells.
 */
timezone: string, 
/**
 * Exactly 168 row-major entries: `dow * 24 + hour`, with Sunday at row zero.
 */
cells: Array<number>, 
/**
 * Highest non-zero play count in any cell.
 */
peak?: number | null, };
