// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a column should be rendered, decided server-side from what it actually holds.
 *
 * The client cannot infer this: a `TEXT` column holding a sha256 and one holding a display name
 * are the same type on the wire, and only the table definition knows which is which.
 */
export type ColumnKind = "text" | "number" | "bool" | "timestamp" | "uuid" | "image" | "json" | "bytes";
