// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TasteSummary } from "./TasteSummary";
import type { TopItem } from "./TopItem";

/**
 * Taste-compatibility between the caller and another user: a 0 to 1 overlap score plus the artists
 * they share. Only returned when the other user's privacy permits it.
 */
export type Compatibility = { user_id: string, handle: string, display_name: string, 
/**
 * Cosine similarity (0.0 to 1.0) over the two users' top-artist play vectors.
 */
score: number, 
/**
 * Artists both users have played, most-shared first (capped).
 */
shared_artists: Array<TopItem>, 
/**
 * The detailed breakdown behind the score. Present only when the VIEWER's plan includes
 * `taste_match_summary`; omitted entirely otherwise, so the free shape is byte-identical to
 * what it was before the field existed.
 */
summary?: TasteSummary | null, };
