// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A figure measured against the equivalent preceding window, so a number can be read as a trend
 * rather than in isolation.
 */
export type Compared = { current: bigint, previous: bigint, 
/**
 * Fractional change, for example `-0.73` for a 73% drop. `None` when `previous` is zero,
 * because percentage change from nothing is undefined; clients should describe this as
 * "new" rather than rendering infinity.
 */
change?: number | null, };
