// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A control on the now-playing message. Each may appear once.
 */
export type ControlButton = "previous" | "play_pause" | "skip" | "stop" | "shuffle" | "loop" | "volume_down" | "volume_up" | "queue" | "autoplay" | "lyrics";
