// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The bar down a container's side.
 */
export type ContainerAccent = { "kind": "bot" } | { "kind": "fixed", hex: string, } | { "kind": "none" };
