// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibraryCoverage } from "./LibraryCoverage";

/**
 * Headline coverage across the libraries a user owns (and optionally those shared with them).
 */
export type CoverageSummary = { 
/**
 * Album-level coverage: owned release-groups / total release-groups across touched artists
 * (0..100). The headline number.
 */
album_pct: number, 
/**
 * Coarse artist-level coverage: artists fully owned / artists touched (0..100).
 */
artist_pct: number, 
/**
 * Release-groups owned across all touched artists (an artist is "touched" if the user owns at
 * least one of their tracks).
 */
owned_rgs: number, 
/**
 * Total release-groups across those artists (from the discography cache).
 */
total_rgs: number, 
/**
 * Artists with at least one owned track that the discography cache has been fetched for.
 */
touched_artists: number, 
/**
 * Of those, how many are fully owned (no missing release-groups).
 */
complete_artists: number, 
/**
 * Artists still awaiting a discography fetch (coverage for them is provisional until fetched).
 */
pending_artists: number, 
/**
 * Per-library owned counts, in priority order.
 */
per_library: Array<LibraryCoverage>, 
/**
 * Libraries the user has excluded from this computation.
 */
excluded_library_ids: Array<string>, 
/**
 * Whether shared-with-me libraries were counted (mirrors [`ManagerPrefs::include_shared`]).
 */
include_shared: boolean, };
