// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlaylistVisibility } from "./PlaylistVisibility";

/**
 * Body of `POST /v1/playlists`.
 *
 * Only `name` is required, and a body of `{"name": "…"}` behaves exactly as it did when that was
 * the whole shape — the two additions are `#[serde(default)]` so an older client keeps working.
 *
 * They exist because creation used to be a one-field prompt, which meant the two decisions that
 * matter most about a playlist were made *after* it existed: a new playlist was public-by-default
 * in effect, since nobody visits a settings dialog to lock down something they just made. Asking
 * once, at the moment of naming, is both fewer steps and a safer default.
 */
export type CreatePlaylistRequest = { name: string, description?: string | null, 
/**
 * Omitted means [`PlaylistVisibility::Private`] — the same thing the column defaults to.
 */
visibility?: PlaylistVisibility | null, };
