// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Credit } from "./Credit";

/**
 * Every credit sharing one role, in the order the source listed them.
 */
export type CreditGroup = { role: string, credits: Array<Credit>, };
