// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreditSource } from "./CreditSource";

/**
 * One person or organisation credited in one role.
 *
 * A person credited for three things is three [`Credit`]s and not one with three roles, because
 * the panel groups by role: a reader looks for "who produced this", not "what did this person do".
 * The library's own parse keeps the other shape (name → roles) since a text file lists it that
 * way; the flattening happens on the way here.
 */
export type Credit = { name: string, 
/**
 * Free text, as the source phrased it — "Producer", "Mix Engineer", "Bass". Deliberately not
 * an enum: MusicBrainz alone has well over a hundred relationship types with attributes on
 * top, and a closed set would silently drop every role it had not anticipated.
 */
role: string, 
/**
 * The catalog artist this credit resolves to, when the Hub already knows the person. Makes the
 * name a link; `None` is the common case for session players who have no releases of their own.
 */
artist_id?: string | null, 
/**
 * A company rather than a person (a label, a studio) — rendered without an avatar.
 */
is_org: boolean, source: CreditSource, };
