// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a credit came from, in precedence order — later variants win a collision.
 */
export type CreditSource = "musicbrainz" | "library_sidecar" | "manual";
