// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A "Made for you" daily mix, a generated station anchored on an artist the user plays. Playing it
 * runs the same radio generation as the artist's radio (`/discovery/radio?artist=seed_artist_id`).
 */
export type DailyMix = { 
/**
 * Display title, e.g. "Daily Mix 1".
 */
title: string, 
/**
 * A few artist names featured in the mix, e.g. "Radiohead, Portishead and more".
 */
subtitle: string, image_url?: string | null, 
/**
 * Artist the mix is seeded from; play the mix by generating radio from this id.
 */
seed_artist_id: string, };
