// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BrowseTrack } from "./BrowseTrack";

/**
 * A daily mix opened as a playlist: its identity plus the generated track list.
 */
export type DailyMixDetail = { seed_artist_id: string, 
/**
 * The seed artist's display name on its own.
 *
 * `title` is already "<Artist> Radio" / "<Artist> Mix", and that is not decomposable in a
 * locale-safe way — so the breadcrumb trail cannot split it into `Artist > Radio` by trimming a
 * suffix. Carrying the bare name costs one field and avoids a second request.
 */
seed_artist_name: string, title: string, subtitle: string, image_url?: string | null, tracks: Array<BrowseTrack>, };
