// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Plays attributed to albums released in one decade.
 */
export type DecadeBucket = { 
/**
 * The decade's first year, for example `1990`.
 */
decade: number, plays: number, ms_played: bigint, };
