// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which installer this is.
 *
 * Deliberately more specific than an operating system: Linux ships two formats and a person on
 * Debian wants the `.deb`, not a choice between two things called "Linux".
 */
export type DesktopPlatform = "windows" | "linux_app_image" | "linux_deb" | "mac_os";
