// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body for `POST /v1/auth/desktop/authorize` — hand the desktop app the session you already have.
 *
 * The desktop app cannot see the website's session: different origin, different storage. So rather
 * than asking someone to sign in a second time, it opens the Hub's own web frontend, where they
 * are usually already signed in, and that page calls this to mint a one-time code for the account
 * it is signed in as. The code goes back over the `chordia://` deep link and is redeemed by
 * [`DesktopExchangeRequest`].
 *
 * This is why the desktop app needs no sign-in method of its own. Whatever the website supports —
 * password, Discord, a second factor, something added later — is what the desktop app supports,
 * without knowing anything about any of it.
 */
export type DesktopAuthorizeRequest = { 
/**
 * SHA-256 (lowercase hex) of the verifier the desktop app is holding.
 */
challenge: string, };
