// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The one-time code to hand back over the deep link. Worthless without the verifier.
 */
export type DesktopAuthorizeResponse = { code: string, };
