// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DesktopPlatform } from "./DesktopPlatform";

/**
 * One installer on the current release.
 */
export type DesktopDownload = { platform: DesktopPlatform, 
/**
 * The asset's own name, shown so somebody can check what they downloaded against the checksums.
 */
filename: string, 
/**
 * An absolute URL on the release host. Not proxied.
 */
url: string, size_bytes: bigint, };
