// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DesktopDownload } from "./DesktopDownload";

/**
 * What the download page renders.
 */
export type DesktopRelease = { 
/**
 * `0.1.5`, without a leading `v`. The same string the updater compares against.
 */
version: string, published_at?: bigint | null, 
/**
 * The release page, for anyone who wants the notes or an asset this list does not name.
 */
notes_url: string, 
/**
 * `SHA256SUMS`, when the release carries one.
 */
checksums_url?: string | null, 
/**
 * Empty when the release host could not be reached. The page says so rather than rendering an
 * empty frame that reads as "there is no desktop app".
 */
downloads: Array<DesktopDownload>, };
