// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The caller's OWN live now-playing entry.
 *
 * This is what lets a signed-in browser say "playing on your phone" instead of "not playing": the
 * Hub already holds one ephemeral entry per user, and this hands the user back their own.
 *
 * Not to be confused with [`crate::room::NowPlaying`], which is a listening-room broadcast, or with
 * [`FriendNowPlaying`], which is somebody else's.
 */
export type DeviceNowPlaying = { 
/**
 * Which device reported it. `None` for a report that predates device ids - a client that
 * cannot attribute an entry must assume it is its own rather than claim a phantom device.
 */
device_id?: string | null, device_label?: string | null, track_id?: string | null, title: string, artist: string, album?: string | null, image_url?: string | null, 
/**
 * When the report landed (epoch millis).
 */
started_at: bigint, };
