// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An artist surfaced by browse-all discovery, with whether the user already owns them.
 */
export type DiscoverArtist = { mbid: string, name: string, 
/**
 * MusicBrainz disambiguation comment (e.g. "UK rock band"), to tell same-named artists apart.
 */
disambiguation?: string | null, image_url?: string | null, 
/**
 * Genres/tags (cached from MusicBrainz/Last.fm), for a "who is this" subtitle on the card.
 */
genres: Array<string>, 
/**
 * True when the user owns this artist in their accessible libraries.
 */
owned: boolean, 
/**
 * The owned-catalog artist id (set only when owned), for linking into the owned artist page.
 */
owned_artist_id?: string | null, 
/**
 * Whether the user already follows this artist.
 */
following: boolean, };
