// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Compared } from "./Compared";
import type { Period } from "./Period";
import type { TopItem } from "./TopItem";

/**
 * How many distinct catalog entities were played and newly discovered in a reporting window.
 */
export type DiscoveryStats = { period: Period, window_start: bigint, window_end: bigint, artists_played: number, artists_played_compared: Compared, artists_new: number, albums_played: number, albums_played_compared: Compared, albums_new: number, tracks_played: number, tracks_played_compared: Compared, tracks_new: number, 
/**
 * Share of window plays whose track was heard before the window (`0.0..=1.0`).
 */
repeat_rate: number, top_new_artists: Array<TopItem>, };
