// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A release-group surfaced by discovery / an artist's full discography, owned-tagged.
 */
export type DiscoverReleaseGroup = { mbid: string, title: string, artist_mbid?: string | null, artist_name?: string | null, primary_type?: string | null, secondary_types: Array<string>, first_release_date?: string | null, cover_url?: string | null, 
/**
 * "instrumental" / "live" version release (from the MB disambiguation / the `Live` secondary type),
 * so the discography can badge it and shelve it apart. Absent for the studio release.
 */
version_type?: string | null, owned: boolean, };
