// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FriendshipStatus } from "./FriendshipStatus";
import type { PublicUser } from "./PublicUser";

/**
 * A discovery hit when searching for people to add.
 */
export type DiscoveryResult = { user: PublicUser, 
/**
 * Existing relationship to the searcher, if any.
 */
relationship?: FriendshipStatus | null, };
