// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Something both listeners first played in the same week.
 */
export type DiscoveredTogether = { 
/**
 * Display name of the shared discovery (an artist).
 */
item: string, 
/**
 * The calendar month the shared first week falls in, `YYYY-MM`.
 */
month: string, };
