// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiscoverArtist } from "./DiscoverArtist";
import type { DiscoverReleaseGroup } from "./DiscoverReleaseGroup";

/**
 * Results of a browse-all search: matching artists and release-groups, owned-first.
 */
export type DiscoverResults = { artists: Array<DiscoverArtist>, release_groups: Array<DiscoverReleaseGroup>, };
