// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DownloadCandidate } from "./DownloadCandidate";
import type { DownloadJobEvent } from "./DownloadJobEvent";
import type { DownloadJobView } from "./DownloadJobView";

/**
 * A job plus its event timeline and any candidates awaiting selection.
 */
export type DownloadJobDetail = { job: DownloadJobView, events: Array<DownloadJobEvent>, candidates: Array<DownloadCandidate>, };
