// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Create/update a quality profile.
 */
export type DownloadQualityProfileInput = { name: string, allowed_formats: Array<string>, cutoff?: string | null, prefer_seeders?: boolean | null, max_size_mb?: number | null, is_default?: boolean | null, };
