// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A scored torrent candidate for interactive selection.
 */
export type DownloadCandidate = { id: string, guid: string, title: string, indexer?: string | null, quality_label?: string | null, score?: number | null, size_bytes?: bigint | null, seeders?: number | null, leechers?: number | null, rank: number, };
