// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ask the Hub to acquire something. `kind` is `album` | `track` | `discography`.
 */
export type DownloadRequestInput = { kind: string, artist_mbid?: string | null, rg_mbid?: string | null, 
/**
 * For `kind="album"`: a specific release (edition) within the release-group to acquire — e.g. the
 * Deluxe edition. When set, the library targets THIS edition (its label steers the search and its
 * tracklist scopes verification) instead of grabbing whatever release satisfies the group.
 */
release_mbid?: string | null, recording_mbid?: string | null, 
/**
 * Destination library. Required only when the user owns more than one acquisition-enabled lib.
 */
library_id?: string | null, quality_profile_id?: string | null, display_title?: string | null, 
/**
 * When true, the library returns scored candidates for the user to pick instead of auto-grabbing.
 */
interactive?: boolean | null, };
