// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One status transition in a job's timeline.
 */
export type DownloadJobEvent = { status: string, detail?: string | null, at: bigint, };
