// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A user's accepted-quality ranking. `allowed_formats` is best-first (e.g.
 * `["flac_hires","flac","mp3_320",…]`); the library scorer ranks candidates by this order.
 */
export type DownloadQualityProfile = { id: string, name: string, 
/**
 * Ordered format keys, best first. Earlier = preferred.
 */
allowed_formats: Array<string>, 
/**
 * Stop hunting for an upgrade once a candidate at/above this format key is found. None = best.
 */
cutoff?: string | null, prefer_seeders: boolean, max_size_mb?: number | null, is_default: boolean, };
