// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A download job as shown in the activity/queue.
 */
export type DownloadJobView = { id: string, request_id: string, library_id: string, status: string, display_title?: string | null, chosen_title?: string | null, quality_label?: string | null, score?: number | null, size_bytes?: bigint | null, seeders?: number | null, 
/**
 * 0..1 download progress.
 */
progress: number, error?: string | null, 
/**
 * The requesting user's handle, set when the viewer isn't the requester (a friend queued this
 * into a library you own, or you queued it into a friend's library — see `library_owner`).
 */
requested_by?: string | null, 
/**
 * The destination library's owner handle, set when the viewer isn't the owner (you requested
 * into a friend's library).
 */
library_owner?: string | null, created_at: bigint, updated_at: bigint, };
