// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClockGrid } from "./ClockGrid";
import type { EntityKind } from "./EntityKind";
import type { Period } from "./Period";
import type { StatsScope } from "./StatsScope";
import type { TopItem } from "./TopItem";

/**
 * Page-only listening detail for one catalog entity. Kept separate from [`EntityStats`] so the
 * lightweight catalog-page panel does not wait on clock and top-list scans.
 */
export type EntityBreakdown = { kind: EntityKind, scope: StatsScope, id: string, period: Period, window_start: bigint, window_end: bigint, 
/**
 * When the caller listens to this entity, in their own timezone.
 */
clock: ClockGrid, 
/**
 * The caller's most-played tracks of this entity: an album's or artist's tracks; empty when
 * the entity is a track.
 */
top_tracks: Array<TopItem>, 
/**
 * An artist's albums by the caller's play count. Empty for album and track.
 */
top_albums: Array<TopItem>, };
