// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Feature } from "./Feature";
import type { PlanTier } from "./PlanTier";

/**
 * Everything a client needs to decide what to show. Served with the profile.
 */
export type Entitlements = { tier: PlanTier, 
/**
 * The capabilities this account actually has. Branch on this, not on `tier`.
 */
features: Array<Feature>, 
/**
 * How far back listening history is readable, in days. `None` = no limit.
 */
retention_days?: number | null, 
/**
 * The oldest timestamp history queries will return, derived from `retention_days`. Lets the UI
 * say "plays before this date are hidden" instead of silently showing a truncated chart.
 */
history_from?: bigint | null, 
/**
 * Start of the current unbroken paid streak. Survives switching tier and switching interval,
 * and survives cancelling then resubscribing before the period runs out; resets only when the
 * subscription actually lapses.
 */
premium_since?: bigint | null, 
/**
 * These entitlements come from an admin/staff comp rather than a payment. No badge is granted:
 * the tier badges mean "supporter", and comping one would make it mean nothing.
 */
complimentary: boolean, 
/**
 * False when this Hub has no payment provider configured. Everything is unlocked, and clients
 * must render no plan UI at all — a self-hoster should never see an upsell.
 */
billing_enabled: boolean, };
