// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BucketGranularity } from "./BucketGranularity";
import type { EntityKind } from "./EntityKind";
import type { Period } from "./Period";
import type { StatsScope } from "./StatsScope";
import type { TimeBucket } from "./TimeBucket";

/**
 * A user's personal listening stats for one catalog entity (artist/album/track). This is the data
 * behind the "your stats" panels on the catalog detail pages.
 */
export type EntityStats = { kind: EntityKind, 
/**
 * Whose plays these figures cover. Echoed back so a page can label itself honestly rather
 * than trusting the toggle it sent.
 */
scope: StatsScope, id: string, period: Period, window_start: bigint, window_end: bigint, granularity: BucketGranularity, total_plays: number, total_ms_played: bigint, 
/**
 * First/last time the user played this entity (epoch millis). `None` if never played.
 */
first_played?: bigint | null, last_played?: bigint | null, 
/**
 * 1-based rank among the user's entities of this kind in the requested period. `None` if the
 * user has never played it in the period.
 */
rank?: number | null, 
/**
 * Number of the user's played entities included in `rank`. `None` when `rank` is `None`.
 */
rank_total?: number | null, 
/**
 * Hub-wide all-time plays from the entity's global rollup. `None` until the rollup has a row.
 */
global_plays?: bigint | null, 
/**
 * Local-calendar play trend (chronological), for a sparkline.
 */
trend: Array<TimeBucket>, };
