// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which kind of catalog entity a per-entity stats query is about.
 */
export type EntityKind = "artist" | "album" | "track";
