// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One parametric EQ band: a peaking filter at `freq` Hz with `gain` dB and quality factor `q`.
 */
export type EqBand = { freq: number, gain: number, q: number, };
