// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EqBand } from "./EqBand";

/**
 * The live equalizer configuration.
 */
export type EqConfig = { enabled: boolean, 
/**
 * Pre-amplifier gain in dB applied before the bands.
 */
preamp: number, bands: Array<EqBand>, };
