// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EqBand } from "./EqBand";

/**
 * A named, saved equalizer preset.
 */
export type EqPreset = { name: string, preamp: number, bands: Array<EqBand>, };
