// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Replace the set of libraries excluded from coverage (body of `PUT /v1/manager/coverage/exclusions`).
 */
export type ExclusionsUpdate = { library_ids: Array<string>, };
