// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One track of the release a download job targets, as MusicBrainz has it.
 *
 * Everything here was known at the moment the job was queued. Carrying it to the library is what
 * lets an import be verified against, and stamped with, the release it was actually asked for.
 */
export type ExpectedTrack = { 
/**
 * Canonical title from MusicBrainz — not from the uploader's tags.
 */
title: string, 
/**
 * Track length. `None` when MusicBrainz has no duration for the recording.
 */
length_ms?: number | null, recording_mbid?: string | null, 
/**
 * The recording's ISRC, which is what lyrics are keyed by.
 */
isrc?: string | null, disc_no?: number | null, 
/**
 * Position on its medium (1-based).
 */
position?: number | null, };
