// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExplorerColumn } from "./ExplorerColumn";

/**
 * A table the explorer will show, and what it looks like.
 */
export type ExplorerTable = { 
/**
 * The key the API takes. Never a raw table name from the caller.
 */
key: string, label: string, 
/**
 * How many rows, counted up to a cap rather than estimated.
 *
 * This was `reltuples`, the planner's estimate, and it was wrong in the way estimates are
 * always wrong at small scale: `reltuples` is -1 until ANALYZE has run on the table, so a
 * three-row table reported zero. An operator cannot tell a real zero from an unanalyzed one,
 * which makes the whole figure worthless. A capped count is exact where it matters and honest
 * where it stops.
 */
row_count: bigint, 
/**
 * `row_count` hit the cap and the real figure is higher.
 */
row_count_capped: boolean, columns: Array<ExplorerColumn>, 
/**
 * The column whose value titles a row in the detail view.
 */
title_column: string, 
/**
 * The image column, when the table has one.
 */
image_column?: string | null, 
/**
 * What the table costs on disk, indexes and TOAST included.
 */
size_bytes: bigint, };
