// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExplorerColumn } from "./ExplorerColumn";

/**
 * A table the explorer will show, and what it looks like.
 */
export type ExplorerTable = { 
/**
 * The key the API takes. Never a raw table name from the caller.
 */
key: string, label: string, 
/**
 * Roughly how many rows, from the planner's statistics rather than a count.
 */
approx_rows: bigint, columns: Array<ExplorerColumn>, 
/**
 * The column whose value titles a row in the detail view.
 */
title_column: string, 
/**
 * The image column, when the table has one.
 */
image_column?: string | null, };
