// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExplorerRow } from "./ExplorerRow";
import type { ExplorerTable } from "./ExplorerTable";

/**
 * One page of a table.
 */
export type ExplorerPage = { table: ExplorerTable, rows: Array<ExplorerRow>, 
/**
 * Rows matching the filter. Exact — the pages are small and an operator paging to the end of a
 * wrong estimate is worse than the count.
 */
total: bigint, queried_at_ms: bigint, };
