// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row, as display values.
 *
 * Everything is a string (or absent for NULL) rather than a typed union: the explorer renders
 * values, it does not compute with them, and a `Vec<serde_json::Value>` would put `any` in the
 * TypeScript for no gain. `ColumnKind` already says how to draw each one.
 */
export type ExplorerRow = { 
/**
 * Primary key, for the detail view and for React keys.
 */
id: string, cells: Array<string | null>, };
