// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColumnKind } from "./ColumnKind";

/**
 * One column of a browsable table.
 */
export type ExplorerColumn = { name: string, kind: ColumnKind, 
/**
 * Whether `ORDER BY` accepts this column. Sorting an unindexed text column on a large table is
 * a sequential scan an operator did not ask for.
 */
sortable: boolean, 
/**
 * Whether the free-text filter searches this column.
 */
searchable: boolean, };
