// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiscoverReleaseGroup } from "./DiscoverReleaseGroup";

/**
 * A not-necessarily-owned artist's page in discovery: identity + full discography, owned-overlaid.
 */
export type ExtArtistDetail = { mbid: string, name: string, disambiguation?: string | null, image_url?: string | null, 
/**
 * Short artist biography (cached from Last.fm), shown on the external artist page.
 */
bio?: string | null, 
/**
 * Genres/tags (cached from MusicBrainz/Last.fm).
 */
genres: Array<string>, owned_artist_id?: string | null, 
/**
 * The catalog `artists` row this discovered artist resolves to (created on demand). Editable via
 * the normal admin metadata tools; this is how Manager artist metadata is modified.
 */
catalog_artist_id?: string | null, following: boolean, 
/**
 * True while the discography is still being fetched from MusicBrainz (list is provisional).
 */
refreshing: boolean, release_groups: Array<DiscoverReleaseGroup>, };
