// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One recording (track) in a cached release-group's listing.
 */
export type ExtRecording = { recording_mbid: string, title: string, disc_no: number, position: number, length_ms?: number | null, 
/**
 * Whether the user owns this track (matched by recording MBID, or title + duration ±2s).
 */
owned: boolean, };
