// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A release-group from an artist's discography cache (may be owned or missing).
 */
export type ExtReleaseGroup = { 
/**
 * MusicBrainz release-group MBID.
 */
mbid: string, title: string, 
/**
 * MusicBrainz primary-type: `"Album"` | `"EP"` | `"Single"` | …
 */
primary_type?: string | null, 
/**
 * secondary-types (`"Live"`, `"Compilation"`, …) the UI can filter on.
 */
secondary_types: Array<string>, 
/**
 * First release date, ISO `YYYY-MM-DD` (may be a partial date padded to the 1st).
 */
first_release_date?: string | null, 
/**
 * Cover Art Archive cover, if fetched (Hub-relative image URL).
 */
cover_url?: string | null, track_total?: number | null, };
