// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A capability an account may or may not have.
 *
 * Deliberately a flat list rather than a tier comparison at the call site: `has(SmartPlaylists)`
 * survives a tier being renamed, split or comped, where `tier >= Sonic` does not.
 */
export type Feature = "custom_accent" | "dynamic_accent" | "name_accent" | "profile_accent" | "animated_avatar" | "smart_playlists" | "taste_match_summary" | "deep_analytics" | "csv_export" | "scrobble_editing";
