// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Five normalized measures of listening behaviour over one local-calendar reporting window.
 */
export type Fingerprint = { 
/**
 * `1 - Gini` of daily play counts across every calendar day in the window, including silent
 * days. `1.0` means every day has the same play count; an empty window is `0.0`.
 */
consistency: number, 
/**
 * Distinct resolved artists, albums, and tracks first heard in the window divided by all
 * distinct resolved artists, albums, and tracks played in it. The three entity kinds share
 * one denominator; an empty denominator is `0.0`.
 */
discovery: number, 
/**
 * Resolved-track plays after that track's first play in the window divided by all resolved-
 * track plays in the window. `0.7` means 70% of resolved plays repeated a track already heard
 * during this window.
 */
replay: number, 
/**
 * Normalized Herfindahl-Hirschman Index of resolved artist play shares:
 * `(HHI - 1/n) / (1 - 1/n)`. `0.0` is an even split across the `n` artists and `1.0` is a
 * single artist; no resolved artists is `0.0`.
 */
concentration: number, 
/**
 * Population coefficient of variation of daily play counts, including silent days, mapped to
 * `CV / (1 + CV)`. `0.0` is identical volume every day; values approach `1.0` as day-to-day
 * volume becomes more volatile. An empty window is `0.0`.
 */
variance: number, };
