// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Fingerprint } from "./Fingerprint";

/**
 * A user's listening fingerprint and, when available, the arithmetic mean of fingerprints for
 * Hub users with at least 20 plays in the same window.
 */
export type FingerprintReport = { you: Fingerprint, 
/**
 * Omitted when no Hub user meets the minimum sample size; never synthesized.
 */
global_average?: Fingerprint | null, };
