// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PublicUser } from "./PublicUser";

/**
 * One row in a followers / following list, carrying the viewer's relationship to that account so
 * the row can render its own follow button without a second round trip.
 */
export type FollowUser = { user: PublicUser, 
/**
 * The viewer follows this account.
 */
viewer_follows: boolean, 
/**
 * This account follows the viewer.
 */
follows_viewer: boolean, 
/**
 * The viewer and this account are accepted friends.
 */
is_friend: boolean, };
