// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A followed artist, as shown in the follows list.
 */
export type FollowedArtist = { artist_mbid: string, name?: string | null, image_url?: string | null, owned_artist_id?: string | null, monitor_types: Array<string>, created_at: bigint, };
