// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Follow an artist / update a follow (body of `POST /v1/manager/follows`, `PATCH .../{mbid}`).
 */
export type FollowInput = { artist_mbid: string, name?: string | null, monitor_types?: Array<string> | null, };
