// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FollowUser } from "./FollowUser";

/**
 * One page of a followers / following list.
 */
export type FollowPage = { items: Array<FollowUser>, 
/**
 * Total edges, so the header can show a count without walking every page.
 */
total: number, 
/**
 * Offset to request next. `None` when this is the last page.
 */
next_offset?: number | null, };
