// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserFlair } from "./UserFlair";

/**
 * One entry in the friends' recent-activity feed, a play by a friend whose privacy allows it.
 */
export type FriendScrobble = { user_id: string, handle: string, display_name: string, avatar_url?: string | null, 
/**
 * The name colour, resolved by the Hub. Same reason as [`crate::social::FriendNowPlaying`]:
 * this feed rendered names in plain text beside lists that coloured the same people.
 */
flair?: UserFlair | null, title: string, artist: string, image_url?: string | null, played_at: bigint, };
