// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserFlair } from "./UserFlair";

/**
 * A friend's currently-playing track (for the live "Listening now" feed). Only friends whose
 * scrobble privacy allows it are included.
 */
export type FriendNowPlaying = { user_id: string, handle: string, display_name: string, avatar_url?: string | null, 
/**
 * The name colour, resolved by the Hub exactly as it is for a [`crate::user::PublicUser`].
 *
 * Without it this rail was one of the surfaces that rendered a paid account's name in plain
 * text while the friends list beside it coloured the same person. The field is what the client
 * needs; the entitlement decision stays server-side.
 */
flair?: UserFlair | null, title: string, artist: string, image_url?: string | null, 
/**
 * When the track started (epoch millis).
 */
started_at: bigint, };
