// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry in the friends' recent-activity feed, a play by a friend whose privacy allows it.
 */
export type FriendScrobble = { user_id: string, handle: string, display_name: string, avatar_url?: string | null, title: string, artist: string, image_url?: string | null, played_at: bigint, };
