// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A friend's currently-playing track (for the live "Listening now" feed). Only friends whose
 * scrobble privacy allows it are included.
 */
export type FriendNowPlaying = { user_id: string, handle: string, display_name: string, avatar_url?: string | null, title: string, artist: string, image_url?: string | null, 
/**
 * When the track started (epoch millis).
 */
started_at: bigint, };
