// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Send a friend request by handle.
 */
export type FriendRequest = { target_handle: string, };
