// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FriendshipStatus } from "./FriendshipStatus";

/**
 * A friendship edge as returned by the Hub. `user_a` is always the lexicographically smaller id
 * so each undirected edge has a single canonical row.
 */
export type Friendship = { user_a: string, user_b: string, status: FriendshipStatus, 
/**
 * Who initiated the pending request (for UI: incoming vs outgoing).
 */
requested_by: string, created_at: bigint, };
