// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One genre in the browse grid. Spellings are folded (see `slug`), so "hip hop", "Hip-Hop" and
 * "hip-hop" arrive as a single row.
 */
export type GenreSummary = { 
/**
 * Fold key: lowercased, non-alphanumerics collapsed to single spaces. The URL segment.
 */
slug: string, 
/**
 * The most common spelling among the folded variants, for display.
 */
name: string, album_count: number, artist_count: number, 
/**
 * Cover of the most-played album carrying this genre, as the tile's art.
 */
image_url?: string | null, };
