// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BrowseAlbum } from "./BrowseAlbum";
import type { BrowseArtist } from "./BrowseArtist";
import type { BrowseTrack } from "./BrowseTrack";

/**
 * A genre page: the artists, albums and tracks that carry it, ranked by plays across the hub —
 * the shape a listener expects from a tag page.
 */
export type GenreDetail = { slug: string, name: string, 
/**
 * Every spelling folded into this genre, so the page can be honest about what it merged.
 */
variants: Array<string>, album_count: number, artist_count: number, top_artists: Array<BrowseArtist>, top_albums: Array<BrowseAlbum>, top_tracks: Array<BrowseTrack>, };
