// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One local-calendar bucket of exclusive album-genre play counts.
 */
export type GenreTrendBucket = { start: bigint, 
/**
 * Counts parallel to [`GenreTrend::genres`], including its trailing `"other"` count.
 */
plays: Array<number>, };
