// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GenreTrendBucket } from "./GenreTrendBucket";

/**
 * Exclusive album-genre shares over time. Albums may carry multiple genres; for a stacked chart,
 * each play is assigned once to the highest-ranked top genre on its album. Plays whose album has
 * none of the top genres, including unresolved albums and albums without genres, go to the
 * trailing literal `"other"` entry.
 */
export type GenreTrend = { 
/**
 * Top album genres in descending whole-window play order, followed by `"other"`.
 */
genres: Array<string>, 
/**
 * Chronological buckets. Every `plays` vector is parallel to `genres` and sums to all plays in
 * that time bucket.
 */
buckets: Array<GenreTrendBucket>, };
