// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionLevel } from "./PermissionLevel";
import type { ServerEndpoint } from "./ServerEndpoint";

/**
 * A minted capability token + the resolved server to present it to.
 */
export type GrantResponse = { token: string, server: ServerEndpoint, expires_at: bigint, 
/**
 * The level this grant carries, signed into the token as well. Clients read it to know
 * whether keeping a copy is allowed at all: `Read` is stream-only, and the library refuses a
 * download-shaped request made with such a token.
 */
permission_level: PermissionLevel, };
