// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServerEndpoint } from "./ServerEndpoint";

/**
 * A minted capability token + the resolved server to present it to.
 */
export type GrantResponse = { token: string, server: ServerEndpoint, expires_at: bigint, };
