// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the small line under a header says.
 */
export type HeaderSubtitle = "channel" | "bot" | "none";
