// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Heartbeat a library posts to the Hub on a fixed interval to stay "online" and keep its
 * endpoint/fingerprint current (handles dynamic IPs).
 */
export type HeartbeatRequest = { server_id: string, endpoint: string, tls_fingerprint: string, };
