// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Hub response to a heartbeat.
 */
export type HeartbeatResponse = { ok: boolean, 
/**
 * Seconds until the next expected heartbeat (the reaper marks stale servers offline).
 */
next_interval_secs: number, };
