// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HistoryEntry } from "./HistoryEntry";

/**
 * A page of scrobble history, newest first, with a keyset cursor for the next page.
 */
export type HistoryPage = { entries: Array<HistoryEntry>, 
/**
 * Pass these back as `before_ms` / `before_id` to fetch the next page. Both `None` at the end.
 */
next_before_ms?: bigint | null, next_before_id?: string | null, };
