// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry in the full scrobble history feed.
 */
export type HistoryEntry = { 
/**
 * The play event's idempotency id (also the keyset-pagination tiebreak).
 */
event_id: string, 
/**
 * Resolved catalog track id, if the play matched the catalog.
 */
track_id?: string | null, title: string, artist: string, album?: string | null, image_url?: string | null, played_at: bigint, ms_played: bigint, };
