// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One local hour of day's plays, yours against theirs.
 */
export type HourSplit = { 
/**
 * Local hour of day, 0 to 23.
 */
hour: number, you: bigint, them: bigint, };
