// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response of `POST /v1/catalog/identify`: the identity AcoustID and MusicBrainz agree on for a
 * fingerprint, as far as it could be resolved.
 *
 * Only [`acoustid`](Self::acoustid) is guaranteed. Everything else is `None` when unresolved and is
 * omitted from the JSON entirely — see the module docs: absent means "not resolved", so a consumer
 * backfills (`COALESCE`) and never overwrites a known value with a blank. If AcoustID knows the
 * fingerprint but has no linked recording, an `IdentifyResponse` with only `acoustid` set is still
 * worth storing: the AcoustID id alone is the strongest own-copy match layer, since two encodings
 * of one recording share it.
 */
export type IdentifyResponse = { 
/**
 * The AcoustID id of the best-scoring match. Stable across encodings of the same recording,
 * which is what makes it the top layer of [`crate::catalog::TrackFingerprint`].
 */
acoustid: string, 
/**
 * MusicBrainz Recording id of the chosen recording. `None` when the AcoustID id has no linked
 * recording yet (a real and fairly common state for new or obscure releases).
 */
recording_mbid?: string | null, 
/**
 * Canonical album title of the matched release, from MusicBrainz rather than from the file.
 * This is the field that gives an `album_id IS NULL` import an album at all.
 */
album?: string | null, 
/**
 * MusicBrainz Release id of the matched release (the specific edition, not the release group).
 */
release_mbid?: string | null, 
/**
 * Artist credited for the matched *release* — the album artist, which on a compilation or a
 * split differs from the track's own artist.
 */
album_artist?: string | null, 
/**
 * Canonical recording title from MusicBrainz. Useful even when the file has a TITLE tag, since
 * the canonical form is what other libraries will have normalized against.
 */
title?: string | null, 
/**
 * Track position on the matched release's medium (1-based). `None` when the release lists no
 * position for this recording.
 */
track_no?: number | null, 
/**
 * Medium (disc) position on the matched release (1-based).
 */
disc_no?: number | null, 
/**
 * Release year of the matched release. `None` when MusicBrainz has no date, a partial date
 * without a year, or a year outside the representable range — the Hub drops such values rather
 * than truncating them into a plausible-looking wrong answer.
 */
year?: number | null, };
