// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body of `POST /v1/catalog/identify`: one track's acoustic fingerprint plus whatever the file already
 * claims about itself.
 *
 * The hints are not filters — the Hub always asks AcoustID about the fingerprint. They break ties
 * among the competing recordings a single AcoustID id can map to (one song appears on an album, a
 * deluxe edition, three compilations and a live record, each a different MusicBrainz recording with
 * a different track position). Matching the hinted album is the strongest of those signals: it is
 * what makes a FLAC and an MP3 of the same track converge on one `recording_mbid`. All three are
 * optional and are routinely absent — an untagged import with no ALBUM tag is precisely the case
 * this endpoint exists to rescue.
 */
export type IdentifyRequest = { 
/**
 * The Chromaprint fingerprint as emitted by `fpcalc -json` (base64-ish, URL-safe).
 *
 * A lossy acoustic hash of the decoded audio, **not audio** — see the module docs. This is the
 * only reason an identification request may leave the library host at all.
 */
fingerprint: string, 
/**
 * Decoded duration in milliseconds, as reported by `fpcalc` alongside the fingerprint.
 *
 * AcoustID matches on duration as well as fingerprint, so this must be the duration `fpcalc`
 * measured, not one read from a tag. Milliseconds to match every other duration in these
 * contracts; the Hub converts to the whole seconds AcoustID expects.
 */
duration_ms: number, 
/**
 * The file's current TITLE tag, if any.
 */
title?: string | null, 
/**
 * The file's current ARTIST tag, if any.
 */
artist?: string | null, 
/**
 * The file's current ALBUM tag, if any. The strongest disambiguation hint when present, and the
 * one most often missing on the imports that need identifying.
 */
album?: string | null, };
