// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a picture comes from.
 */
export type ImageSource = { "kind": "cover" } | { "kind": "artist" } | { "kind": "artist_banner" } | { "kind": "bot_avatar" } | { "kind": "server_icon" } | { "kind": "equalizer" } | { "kind": "url", url: string, };
