// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which service an uploaded history file came from.
 *
 * Detected from the file's content server-side; a client may also state it explicitly
 * (`POST /v1/me/imports?source=`), which is validated against the content rather than trusted.
 */
export type ImportSource = "spotify" | "lastfm";
