// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportJob } from "./ImportJob";

/**
 * `GET /v1/me/imports`: the caller's recent import jobs, newest first.
 */
export type ImportJobsResponse = { jobs: Array<ImportJob>, };
