// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportJobStatus } from "./ImportJobStatus";
import type { ImportSource } from "./ImportSource";

/**
 * One history-import job, as created by `POST /v1/me/imports` and polled from
 * `GET /v1/me/imports/{id}`.
 *
 * The counters partition `total_rows`: every row in the file ends up imported, a duplicate of an
 * already-stored event, or skipped (sub-30-second Spotify plays, podcast rows, unparseable rows).
 * `matched_rows` counts, among the imported, those resolved to a catalog track; the rest are
 * stored with their artist/title text and match later if that music arrives.
 */
export type ImportJob = { id: string, source: ImportSource, status: ImportJobStatus, 
/**
 * Rows found in the file. `0` until parsing finishes.
 */
total_rows: number, 
/**
 * Rows inserted as new listening events so far.
 */
imported_rows: number, 
/**
 * Rows that were already present (same deterministic event id), so nothing was inserted.
 */
duplicate_rows: number, 
/**
 * Imported rows resolved to a track in a library the owner can access.
 */
matched_rows: number, 
/**
 * Rows not worth importing: sub-30-second Spotify plays, podcast rows, unparseable rows.
 */
skipped_rows: number, 
/**
 * A stable failure code (`"malformed"`, `"internal"`, ...) when `status` is `Failed`; clients
 * localize it.
 */
error?: string | null, created_at: bigint, finished_at?: bigint | null, };
