// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lifecycle of an import job. Terminal states are `Done` and `Failed`; a client polls until it
 * reaches one.
 */
export type ImportJobStatus = "pending" | "running" | "done" | "failed";
