// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Instance-level capability flags the client needs before it renders social surfaces.
 */
export type InstanceInfo = { 
/**
 * Whether the follow graph and public profiles are enabled on this instance.
 */
social_enabled: boolean, };
