// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a Hub says about itself to a client that has not signed in — capability flags, plus enough
 * identity for the desktop app's hub picker.
 *
 * Unauthenticated by necessity: the desktop app calls this on a URL the user has just typed, to
 * answer "is this a Chordia Hub, what do we call it, and does it do Discord" before there is any
 * account here to authenticate with. A 200 with this shape is itself the "yes, this is a Hub"
 * check.
 */
export type InstanceInfo = { 
/**
 * Whether the follow graph and public profiles are enabled on this instance.
 */
social_enabled: boolean, 
/**
 * Operator-facing name, shown in the desktop hub picker. Self-hosters run several, and "Hub"
 * three times is not a picker.
 */
name: string, 
/**
 * Hub software version, for support and for a client that wants to warn about a stale server.
 */
version: string, 
/**
 * The Hub's canonical **web** frontend. The desktop app anchors the links its users copy here,
 * because its own origin (`https://tauri.localhost`) means nothing to whoever receives one.
 */
frontend_url: string, 
/**
 * Whether "Continue with Discord" will work here. False when the operator never configured a
 * Discord app, and a button that leads to a 500 is worse than no button.
 */
discord_oauth: boolean, 
/**
 * The accent this deployment wears before a listener has chosen their own — a preset name or a
 * `#rrggbb`. `None` means the operator has not set one and the app's own default stands, which
 * is different from their choosing that colour: it keeps following the default if it changes.
 *
 * Public because it themes the sign-in and landing screens, which nobody is signed in to.
 */
accent?: string | null, };
