// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CandidateInput } from "./CandidateInput";

/**
 * Body of `POST /v1/manager/jobs/{id}/candidates`.
 */
export type JobCandidates = { candidates: Array<CandidateInput>, };
