// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body of `POST /v1/manager/jobs/claim`. The library asks for up to `max` queued jobs.
 */
export type JobClaimRequest = { server_id: string, max: number, };
