// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body of `POST /v1/manager/jobs/{id}/status`: a status transition reported by the library.
 */
export type JobStatusUpdate = { status: string, progress?: number | null, chosen_guid?: string | null, chosen_title?: string | null, quality_label?: string | null, score?: number | null, size_bytes?: bigint | null, seeders?: number | null, qbit_hash?: string | null, error?: string | null, detail?: string | null, };
