// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BrowseAlbum } from "./BrowseAlbum";

/**
 * A label page: its identity, enriched metadata, and the albums released on it (within accessible
 * libraries).
 */
export type LabelDetail = { 
/**
 * None for the synthetic "Unlabeled" view.
 */
id?: string | null, name: string, mbid?: string | null, logo_url?: string | null, description?: string | null, 
/**
 * Founded / dissolved, raw MB partial dates (`YYYY` | `YYYY-MM` | `YYYY-MM-DD`).
 */
founded?: string | null, defunct?: string | null, country?: string | null, 
/**
 * MB label type: `"Production"`, `"Original Production"`, `"Imprint"`, …
 */
label_type?: string | null, 
/**
 * Former names merged into this canonical label (e.g. "Warner Bros. Records" became "Warner Records").
 */
former_names: Array<string>, albums: Array<BrowseAlbum>, };
