// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A music label in the browse-by-label index.
 */
export type LabelSummary = { 
/**
 * None marks the synthetic "Unlabeled" bucket.
 */
id?: string | null, name: string, 
/**
 * Label logo (fanart.tv), if enriched.
 */
logo_url?: string | null, album_count: number, };
