// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body of `POST /v1/lastfm/session`: the single-use web-auth token from the Last.fm callback,
 * which the Hub exchanges (signed) for the user's permanent session key.
 */
export type LastfmSessionRequest = { token: string, };
