// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A user's Last.fm connection status, for the settings "Connections" section.
 */
export type LastfmStatus = { connected: boolean, 
/**
 * The connected Last.fm username, when connected.
 */
username?: string | null, };
