// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response of `POST /v1/lastfm/connect`: where to send the browser, and the opaque state value
 * that binds the resulting callback to the user who started the flow.
 *
 * The state also rides in the Last.fm callback URL, so the callback page can compare it against
 * the copy it kept — a `?token=` link from somewhere else carries a state this browser never
 * started with, and is refused before anything is linked.
 */
export type LastfmConnectResponse = { 
/**
 * Last.fm's authorization page, with the Hub's callback (carrying `state`) attached.
 */
authorize_url: string, 
/**
 * Opaque, short-lived, signed value to echo back to `POST /v1/lastfm/session`.
 */
state: string, };
