// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Accessory } from "./Accessory";
import type { ButtonSpec } from "./ButtonSpec";
import type { ImageSource } from "./ImageSource";
import type { SeparatorSpacing } from "./SeparatorSpacing";

/**
 * One part of a message.
 */
export type LayoutBlock = { "kind": "text", content: string, } | { "kind": "section", content: string, accessory: Accessory, } | { "kind": "gallery", images: Array<ImageSource>, } | { "kind": "separator", divider: boolean, spacing: SeparatorSpacing, } | { "kind": "row", buttons: Array<ButtonSpec>, } | { "kind": "list", item: string, empty: string, page_size: number, };
