// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which of the bot's messages a layout describes.
 */
export type LayoutView = "now_playing" | "idle" | "queued" | "left" | "queue" | "history" | "queued_album" | "queued_artist" | "queued_playlist" | "lyrics" | "done" | "notice" | "error" | "vote" | "vote_passed";
