// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ViewLayout } from "./ViewLayout";

/**
 * A server's own versions of some of the bot's messages. A view that is absent means "the
 * bot's". Written by the library owner from the dashboard, per server, in the same language.
 */
export type LayoutOverrides = { 
/**
 * [`LAYOUT_VERSION`] when saved by this code; 0 for anything older.
 */
version: number, now_playing?: ViewLayout | null, idle?: ViewLayout | null, queued?: ViewLayout | null, left?: ViewLayout | null, queue?: ViewLayout | null, history?: ViewLayout | null, queued_album?: ViewLayout | null, queued_artist?: ViewLayout | null, queued_playlist?: ViewLayout | null, lyrics?: ViewLayout | null, done?: ViewLayout | null, notice?: ViewLayout | null, error?: ViewLayout | null, vote?: ViewLayout | null, vote_passed?: ViewLayout | null, equalizer?: ViewLayout | null, session?: ViewLayout | null, };
