// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtPlacement } from "./ArtPlacement";
import type { ControlButton } from "./ControlButton";
import type { HeaderSubtitle } from "./HeaderSubtitle";
import type { MetaLine } from "./MetaLine";
import type { SeparatorSpacing } from "./SeparatorSpacing";

/**
 * One part of a message. Which kinds a view accepts is checked by [`ViewLayout::validate`].
 */
export type LayoutBlock = { "kind": "header", subtitle: HeaderSubtitle, } | { "kind": "track", art: ArtPlacement, album: boolean, badges: boolean, } | { "kind": "progress", 
/**
 * Bar segments; four to twenty. Twelve is about the width of a title on a phone.
 */
cells: number, times: boolean, meta: MetaLine, } | { "kind": "controls", rows: Array<Array<ControlButton>>, } | { "kind": "separator", divider: boolean, spacing: SeparatorSpacing, } | { "kind": "text", content: string, } | { "kind": "summary", art: ArtPlacement, };
