// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether the erasure ledger is actually being kept, and how current it is.
 *
 * Surfaced beside the backup list because the two are one story: an archive without a ledger newer
 * than itself cannot be restored without resurrecting accounts, so a list of backups shown next to
 * a broken ledger is a list of traps.
 */
export type LedgerStatus = { 
/**
 * All four credentials present. False means a restore WILL resurrect deleted accounts.
 */
mirroring: boolean, 
/**
 * Object key being written, when mirroring is on.
 */
object_key?: string | null, 
/**
 * Rows in `account_erasures` right now.
 */
entries: bigint, 
/**
 * The most recent erasure, or `None` if nobody has ever deleted an account.
 */
latest_erasure_ms?: bigint | null, };
