// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Owned counts for one library in the coverage scope.
 */
export type LibraryCoverage = { library_id: string, name: string, 
/**
 * True when this library is owned by the user (false = shared-with-them).
 */
owned: boolean, 
/**
 * Whether this library is currently excluded from coverage math.
 */
excluded: boolean, track_count: number, album_count: number, artist_count: number, };
