// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionLevel } from "./PermissionLevel";
import type { PublicUser } from "./PublicUser";

/**
 * A share grant: which user may access which library, at what level.
 */
export type LibraryShare = { library_id: string, grantee: PublicUser, permission_level: PermissionLevel, 
/**
 * Whether the grantee may queue acquisition (download) requests INTO this library.
 */
can_request: boolean, created_at: bigint, };
