// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BucketGranularity } from "./BucketGranularity";
import type { Period } from "./Period";
import type { StatsScope } from "./StatsScope";
import type { TimeBucket } from "./TimeBucket";
import type { TopItem } from "./TopItem";

/**
 * Listening stats for one library, behind `GET /v1/libraries/{id}/stats`.
 *
 * Its own type rather than a widened [`EntityKind`], for exactly the reason [`PlaylistStats`]
 * gives: a library is not a catalog entity — there is no `libraries` row in the catalog tables at
 * all — and the entity path switches exhaustively over the kind on both sides, so widening it
 * would cost a new arm in every one of those matches plus a client-reachable `kind=library` that
 * every ranked-chart query would then have to refuse.
 *
 * Answers the question a library page cannot answer today: this is where the music actually comes
 * from, and until now the page could say how many tracks it holds and nothing about whether any of
 * them get played.
 *
 * **Storage bytes are absent on purpose.** Only the library server knows file sizes, and the
 * catalog sync payload has never carried them, so any figure here would be invented. Adding a
 * nullable field would put a permanent zero on the page; widening the sync payload is the honest
 * way to get it, and that is a separate change.
 */
export type LibraryStats = { id: string, period: Period, window_start: bigint, window_end: bigint, granularity: BucketGranularity, 
/**
 * Whose plays these figures cover. Echoed back so a panel can label itself honestly rather
 * than trusting the toggle it sent.
 */
scope: StatsScope, total_plays: number, total_ms_played: bigint, first_played?: bigint | null, last_played?: bigint | null, 
/**
 * Distinct listeners in the window — the owner plus everyone they share with. Unlike the
 * playlist equivalent this is meaningful in `Me` scope too, because a library's whole point is
 * that other people stream from it.
 */
unique_listeners?: number | null, 
/**
 * Local-calendar play trend (chronological).
 */
trend: Array<TimeBucket>, top_tracks: Array<TopItem>, top_artists: Array<TopItem>, top_albums: Array<TopItem>, 
/**
 * Tracks this library holds, from the catalog rather than the fact table.
 */
track_count: number, 
/**
 * Distinct tracks of this library played in the window, so the page can say "you have played
 * 412 of 5,120" — the shape of question a personal library invites and a streaming service
 * cannot ask.
 */
tracks_played: number, 
/**
 * When per-library attribution began (epoch millis). Plays recorded before
 * `listening_events.library_id` shipped carry no library context; they are recovered where the
 * track is still held by exactly this library, but that recovery is best-effort and the panel
 * must be able to say so.
 */
tracking_since: bigint, };
