// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Redacted per-library acquisition health (the Hub's mirror of what the library reported).
 */
export type LibraryAcquisitionStatus = { library_id: string, enabled: boolean, indexer_count: number, client_kind?: string | null, last_reported_at?: bigint | null, last_error?: string | null, };
