// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionLevel } from "./PermissionLevel";
import type { PublicUser } from "./PublicUser";
import type { ShareNowStreaming } from "./ShareNowStreaming";

/**
 * Per-grantee share + usage stats for the owner's library management screen ("who has access and
 * what are they doing with it"): the share itself plus request/download/listening activity
 * attributed to THIS library.
 */
export type LibraryShareStats = { library_id: string, grantee: PublicUser, permission_level: PermissionLevel, can_request: boolean, created_at: bigint, 
/**
 * Acquisition requests this friend has queued into this library.
 */
requests_count: number, 
/**
 * How many of those completed (media actually landed in the library).
 */
downloads_completed: number, 
/**
 * Plays this friend has streamed from this library.
 */
plays: number, 
/**
 * Total listening time from this library, in milliseconds.
 */
ms_played: bigint, last_played?: bigint | null, 
/**
 * What they're streaming from this library right now, if anything (and not private).
 */
now_streaming?: ShareNowStreaming | null, };
