// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summary of a logical library as registered with the Hub.
 */
export type LibrarySummary = { id: string, owner_id: string, 
/**
 * Display name, e.g. "Hi-Fi Archive", "Family Collection".
 */
name: string, 
/**
 * The self-hosted server (`server_id`) that physically hosts this library.
 */
server_id: string, 
/**
 * Optional Phosphor icon name chosen by the owner; None → default icon.
 */
icon?: string | null, track_count: number, created_at: bigint, };
