// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OverrideKind } from "./OverrideKind";

/**
 * One override a library owner has set, as their settings page lists them.
 *
 * The point of this shape is that the page could previously only ANSWER "what have I set on this
 * artist" and never "what have I set at all" — the editor was search-first, so an override you
 * forgot about was invisible until you went looking for the exact entity again.
 */
export type LibraryOverrideSummary = { kind: OverrideKind, 
/**
 * The catalog entity the override applies to.
 */
id: string, 
/**
 * What it is called AFTER the override, so the row reads as the library actually shows it.
 */
name: string, 
/**
 * The canonical name, present only when the override CHANGES it. Absent means the name is
 * inherited and the row is showing the catalog's own.
 */
original_name?: string | null, image_url?: string | null, 
/**
 * Field names this override actually sets, so the row can say what was changed rather than
 * only that something was. Names match the override input fields (`title`, `year`, `genres`…).
 */
fields: Array<string>, 
/**
 * Whether this edit also takes over the global catalog.
 */
override_main: boolean, updated_at: bigint, };
