// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One artist's share of the caller's liked songs.
 */
export type LikedArtist = { id: string, name: string, 
/**
 * Liked tracks credited to this artist. Deliberately not a play count — this list answers
 * "whose songs did you keep", which is a different ranking from "whose songs did you play".
 */
liked: number, image_url?: string | null, };
