// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One month in the growth of the caller's liked songs.
 */
export type LikedPoint = { 
/**
 * First day of the month, `YYYY-MM-DD`.
 */
month: string, 
/**
 * Liked tracks held at the END of that month.
 *
 * Counted from the likes that are STILL IN PLACE, because an unlike leaves no record: the row
 * is deleted, so a song liked in March and unliked in April was never here as far as this can
 * tell. The line therefore reads "how your current collection accumulated", not "how many
 * songs you had liked at the time", and those are different questions with the same shape.
 */
total: number, };
