// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LikedArtist } from "./LikedArtist";
import type { LikedPoint } from "./LikedPoint";
import type { TopItem } from "./TopItem";

/**
 * The caller's liked songs in numbers, for the disclosure on the Liked Songs page.
 *
 * Everything derived from listening honours the caller's retention floor, so the ratios below
 * describe the window their insights already show rather than quietly reaching past it.
 */
export type LikedStats = { 
/**
 * Liked tracks right now.
 */
total: number, 
/**
 * Their combined length. `0` when none of them resolve to a catalog track with a duration.
 */
total_duration_ms: bigint, 
/**
 * Oldest and newest like still in place.
 */
first_liked?: bigint | null, last_liked?: bigint | null, 
/**
 * Cumulative growth, one point per month from the first like to now.
 */
history: Array<LikedPoint>, 
/**
 * Distinct tracks the caller has played inside the retention window.
 */
played_tracks: number, 
/**
 * How many of those they went on to like. With `played_tracks` at 0 the ratio is undefined,
 * which is why both numbers are sent rather than a percentage computed here.
 */
played_liked: number, 
/**
 * Liked tracks with no play on record in the window. "Saved for later" made countable.
 */
never_played: number, 
/**
 * The caller's plays across their liked tracks.
 */
liked_plays: bigint, 
/**
 * The caller's most-played tracks that they have NOT liked — the songs the heart missed.
 */
unliked_favourites: Array<TopItem>, 
/**
 * Artists best represented in the liked list.
 */
top_artists: Array<LikedArtist>, };
