// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NowPlayingReport } from "./NowPlayingReport";

/**
 * `POST /v1/directory/now-playing`: what the bot is playing to these listeners right now, or,
 * with no report, that it stopped. The Hub keeps the same live "listening now" entry a client
 * posts for itself, so a listener's profile shows the track. Every user is re-checked against
 * the trust rule.
 */
export type ListenersNowPlaying = { user_ids: Array<string>, report?: NowPlayingReport | null, };
