// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BucketGranularity } from "./BucketGranularity";
import type { ClockGrid } from "./ClockGrid";
import type { Period } from "./Period";
import type { TimeBucket } from "./TimeBucket";

/**
 * Chart-oriented listening data for a period: an activity time series plus the listening-clock
 * (hour-of-day) and weekday distributions. Computed live from the partitioned fact table, scoped
 * to one user over a bounded window.
 */
export type ListeningCharts = { period: Period, window_start: bigint, window_end: bigint, granularity: BucketGranularity, 
/**
 * IANA timezone used for the local calendar window and time buckets.
 */
timezone: string, 
/**
 * Plays bucketed across the window, chronological. Daily for windows up to a year; monthly for
 * `Overall`. Doubles as a calendar-heatmap source at day granularity.
 */
over_time: Array<TimeBucket>, 
/**
 * Plays by local hour-of-day, exactly 24 entries (index = hour 0 to 23).
 */
clock: Array<number>, 
/**
 * Plays by local day-of-week, exactly 7 entries (index 0 = Sunday through 6 = Saturday).
 */
weekday: Array<number>, clock_grid: ClockGrid, };
