// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Compared } from "./Compared";
import type { ListeningSession } from "./ListeningSession";
import type { Milestone } from "./Milestone";
import type { Period } from "./Period";
import type { Streak } from "./Streak";
import type { TimeBucket } from "./TimeBucket";

/**
 * Personal listening records and all-time milestones for one reporting window.
 */
export type ListeningRecords = { period: Period, window_start: bigint, window_end: bigint, timezone: string, longest_streak?: Streak | null, current_streak?: Streak | null, active_days: number, 
/**
 * Mean plays per calendar day in the window, including silent days.
 */
avg_plays_per_day: number, 
/**
 * Current and previous averages rounded to the nearest whole play per day. The precise current
 * value remains available in `avg_plays_per_day`.
 */
avg_plays_per_day_compared: Compared, biggest_day?: TimeBucket | null, 
/**
 * Play count of the busiest local-calendar day in each window (zero when a window is empty).
 */
biggest_day_compared: Compared, 
/**
 * Longest sessions first, capped at ten.
 */
top_sessions: Array<ListeningSession>, 
/**
 * Round-number play milestones, ascending.
 */
milestones: Array<Milestone>, first_scrobble?: Milestone | null, 
/**
 * True when the day-grained figures could not be computed yet: the UTC report is served from
 * the daily rollup, and on a Hub whose aggregator has never completed a pass there is no
 * rollup to read. The streaks, `active_days`, the averages and `biggest_day` above are then
 * placeholders rather than facts, and a client should say "still being computed" instead of
 * rendering a zero-day history as if it were real. Sessions and milestones are unaffected
 * (they scan the fact table directly), as are non-UTC reports.
 */
day_stats_pending: boolean, };
