// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientType } from "./ClientType";
import type { PlaybackSource } from "./PlaybackSource";
import type { TrackFingerprint } from "./TrackFingerprint";

/**
 * A single listening event. Created client-side with a UUIDv7 `event_id` so it doubles as the
 * **idempotency key** - replays/reinstalls never double-count.
 */
export type ListeningEvent = { 
/**
 * UUIDv7 - time-sortable + idempotency key.
 */
event_id: string, 
/**
 * Identity of what was played (resolved to the canonical catalog server-side).
 */
fingerprint: TrackFingerprint, 
/**
 * Track title exactly as reported by the client. Optional for compatibility with older clients;
 * resolved events can fall back to the canonical catalog title.
 */
title?: string | null, 
/**
 * Artist display string exactly as reported by the client. This is deliberately distinct from
 * `fingerprint.artist_norm`, which is only a fuzzy-matching key.
 */
artist?: string | null, 
/**
 * When playback started (epoch millis, client clock).
 */
started_at: bigint, 
/**
 * Milliseconds actually played.
 */
ms_played: number, 
/**
 * Track duration for threshold/skew calculations.
 */
duration_ms: number, source: PlaybackSource, client_type: ClientType, 
/**
 * Library streamed from, when applicable.
 */
library_id?: string | null, 
/**
 * Room the track was heard in, when applicable.
 */
room_id?: string | null, 
/**
 * Playlist the track was played from, when the play originated in a playlist context.
 */
playlist_id?: string | null, };
