// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A continuous listening session, split after a 30-minute idle gap.
 */
export type ListeningSession = { started_at: bigint, ended_at: bigint, tracks: number, ms_played: bigint, top_artist?: string | null, };
