// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BrowseTrack } from "./BrowseTrack";

/**
 * A synthesized per-artist "Live" collection: every owned live-version album track plus owned
 * live bonus variants scattered across the artist's other releases. Not a real `albums` row —
 * keyed on the artist (like `DailyMixDetail` is keyed on its seed), so it always reflects the
 * current library. The client localizes the display title/subtitle.
 */
export type LiveAlbum = { artist_id: string, artist_name: string, image_url?: string | null, 
/**
 * Ordered by source album date, then disc/track position.
 */
tracks: Array<BrowseTrack>, 
/**
 * Distinct source albums the tracks were drawn from (for the localized subtitle).
 */
source_album_count: number, };
