// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the server's disk holds, and how much room is left on it.
 */
export type LocalStatus = { archives: bigint, 
/**
 * Total size of the archives themselves, not of the directory.
 */
total_bytes: bigint, 
/**
 * Free space on the volume the backups directory lives on. `None` when it could not be read.
 *
 * The number that decides whether tonight's backup succeeds. A backup system that reports its
 * own size but not the room left beside it answers the less useful of the two questions.
 */
free_bytes?: bigint | null, 
/**
 * What the newest archive weighs, as the best available estimate of what the next one will.
 */
newest_bytes?: bigint | null, };
