// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A credential request (email + password) against the Hub.
 */
export type LoginRequest = { email: string, password: string, 
/**
 * When set, the Hub issues a long-lived ("remember me") refresh token.
 */
remember: boolean, };
