// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One lyric line. `start_ms`/`end_ms` are present only for [`LyricsSyncType::LineSynced`].
 */
export type LyricsLine = { text: string, 
/**
 * Line start offset from the top of the track, in milliseconds.
 */
start_ms?: number | null, 
/**
 * Line end offset, in milliseconds.
 */
end_ms?: number | null, };
