// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * User-supplied lyrics edit (`PUT /v1/lyrics/{track_id}`). The body is raw text the server parses:
 * when `synced`, each line is LRC (`[mm:ss.xx] words`); otherwise lines are plain text.
 */
export type LyricsEditInput = { 
/**
 * Whether `text` is timed LRC (`true`) or plain lines (`false`).
 */
synced: boolean, 
/**
 * The lyrics body: LRC lines when `synced`, else one plain line per newline.
 */
text: string, };
