// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether the lyric lines carry per-line timing.
 */
export type LyricsSyncType = "UNSYNCED" | "LINE_SYNCED";
