// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LyricsLine } from "./LyricsLine";
import type { LyricsSyncType } from "./LyricsSyncType";

/**
 * Lyrics for a single track, as served by `GET /v1/lyrics/{track_id}`.
 */
export type Lyrics = { track_id: string, sync_type: LyricsSyncType, lines: Array<LyricsLine>, 
/**
 * YouTube video id captured alongside the lyrics, for future video support. May be absent.
 */
youtube_video_id?: string | null, 
/**
 * True when a user set/edited these lyrics by hand (the auto-fetcher won't overwrite them).
 */
manually_edited: boolean, };
