// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-user Manager preferences.
 */
export type ManagerPrefs = { 
/**
 * Count shared-with-me libraries toward coverage.
 */
include_shared: boolean, 
/**
 * Default destination library for downloads.
 */
default_library_id?: string | null, 
/**
 * Default quality profile id.
 */
default_quality_profile_id?: string | null, 
/**
 * One-time acknowledgement that the user is responsible for content legality (gates downloads).
 */
acq_ack: boolean, };
