// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-user Manager preferences.
 */
export type ManagerPrefs = { 
/**
 * Count shared-with-me libraries toward coverage.
 */
include_shared: boolean, 
/**
 * Default library to scope Manager views to.
 */
default_library_id?: string | null, };
