// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which identity layer produced an own-copy hit.
 */
export type MatchStrength = "acoustid" | "recording_mbid" | "content_hash" | "fuzzy_metadata";
