// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Own-copy lookup query (`GET /v1/tracks/match`). Any subset may be provided; the library tries
 * from strongest to weakest.
 */
export type MatchQuery = { acoustid?: string | null, recording_mbid?: string | null, content_hash?: string | null, artist_norm?: string | null, title_norm?: string | null, duration_ms?: number | null, };
