// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MatchStrength } from "./MatchStrength";
import type { Track } from "./Track";

/**
 * Own-copy lookup result.
 */
export type MatchResult = { 
/**
 * The matched local track, if any.
 */
track?: Track | null, 
/**
 * Which fingerprint layer produced the hit, for telemetry and UX confidence.
 */
matched_on?: MatchStrength | null, };
