// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SuggestionFieldInput } from "./SuggestionFieldInput";

/**
 * Body of `POST /v1/suggestions`: one Report-modal submission. Fans out into one stored, separately
 * reviewable suggestion per item.
 */
export type MetadataSuggestionInput = { 
/**
 * `artist` | `album` | `track`.
 */
entity_type: string, entity_id: string, note?: string | null, items: Array<SuggestionFieldInput>, };
