// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The small line under the progress bar: which facts it carries.
 */
export type MetaLine = { 
/**
 * "Requested by @user", or "Autoplay".
 */
requested_by: boolean, 
/**
 * "3 in queue".
 */
queue: boolean, 
/**
 * "vol 80%", only when not 100.
 */
volume: boolean, 
/**
 * "loop: queue", "shuffle", "autoplay", each only when on.
 */
modes: boolean, };
