// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A notable ordinal play in a user's listening history.
 */
export type Milestone = { ordinal: bigint, played_at: bigint, title: string, artist: string, track_id?: string | null, image_url?: string | null, };
