// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A client's report of what it's currently playing. It's ephemeral, held in memory on the Hub for
 * the live "Listening now" feed, never written to scrobble history.
 */
export type NowPlayingReport = { track_id?: string | null, title: string, artist: string, album?: string | null, image_url?: string | null, };
