// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrackFingerprint } from "./TrackFingerprint";

/**
 * The "now playing" descriptor broadcast to a room. Carries the full layered fingerprint so each
 * listener can run own-copy resolution locally.
 */
export type NowPlaying = { fingerprint: TrackFingerprint, 
/**
 * Display metadata (so clients without an own-copy still render the track).
 */
title: string, artist: string, 
/**
 * The DJ whose library is the relay source of truth.
 */
dj_user_id: string, dj_server_id: string, 
/**
 * Authoritative playhead at `as_of` (room clock).
 */
position_ms: number, as_of: bigint, paused: boolean, };
