// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OnThisDayYear } from "./OnThisDayYear";

/**
 * Listening-history memories whose local date matches today's month and day.
 */
export type OnThisDay = { timezone: string, 
/**
 * Most recent year first.
 */
years: Array<OnThisDayYear>, };
