// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HistoryEntry } from "./HistoryEntry";

/**
 * One past year's plays on today's local month and day.
 */
export type OnThisDayYear = { year: number, plays: number, 
/**
 * Newest-first sample of that day's plays.
 */
entries: Array<HistoryEntry>, };
