// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which catalog table an override points at.
 */
export type OverrideKind = "artist" | "album" | "track";
