// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A server paired to the caller's account, as the owner sees it
 * (`GET /v1/servers`). The API key itself is never included — it is returned exactly once, by
 * pairing, and afterwards only ever replaced by a rotation.
 */
export type PairedServer = { server_id: string, 
/**
 * Last endpoint the server advertised, if it has ever heartbeat.
 */
endpoint?: string | null, 
/**
 * The pinned TLS leaf fingerprint the server last advertised (hex SHA-256).
 */
tls_fingerprint?: string | null, online: boolean, last_heartbeat?: bigint | null, 
/**
 * Names of the logical libraries this server backs. Unpairing the server removes them too,
 * so the owner can see what a revoke would take with it.
 */
libraries: Array<string>, };
