// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Aggregation window for a stats report. Mirrors the Last.fm-style windows: 7-day, 1/3/6/12
 * month, and all-time.
 */
export type Period = "day" | "week" | "month" | "quarter" | "half_year" | "year" | "overall";
