// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a grantee may do with a shared library. Read-only for the MVP; `Download` is reserved.
 */
export type PermissionLevel = "read" | "download";
