// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which catalog entity a pin points at. `Radio` is a generated artist station (the pin's `id` is
 * the seed artist's id); it resolves to a "{Artist} Radio" entry that opens the station page.
 */
export type PinKind = "album" | "artist" | "playlist" | "radio";
