// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PinKind } from "./PinKind";

/**
 * A resolved pin (name + artwork) ready to render in the sidebar.
 */
export type PinnedItem = { kind: PinKind, id: string, name: string, image_url?: string | null, };
