// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A subscription tier. Ordered: every tier includes everything below it.
 */
export type PlanTier = "free" | "sonic" | "super_sonic";
