// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Feature } from "./Feature";
import type { PlanTier } from "./PlanTier";

/**
 * One purchasable plan, for the pricing table.
 */
export type PlanInfo = { tier: PlanTier, features: Array<Feature>, retention_days?: number | null, 
/**
 * Minor units (cents), so no float ever touches a price.
 */
monthly_price_cents: number, yearly_price_cents: number, 
/**
 * ISO 4217, e.g. `USD`.
 */
currency: string, 
/**
 * Absent when this Hub has not configured a product for that interval, which is also how a
 * client knows not to offer it.
 */
monthly_product_id?: string | null, yearly_product_id?: string | null, };
