// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlanInfo } from "./PlanInfo";

/**
 * `GET /v1/billing/plans`. Public: the pricing table is readable signed out.
 */
export type PlansResponse = { billing_enabled: boolean, 
/**
 * Paid plans only — Free is the absence of a subscription, not a product.
 */
plans: Array<PlanInfo>, 
/**
 * How far back Free can read its own listening history, in days. `None` = no limit.
 *
 * Here because Free is not in `plans`, and a comparison table still has to fill that cell. It
 * used to be hard-coded in the client, which is how it came to say one year while the server
 * had been giving everyone two since the window was widened. The prices on this response are
 * read from the server precisely so they cannot drift; the same has to be true of this.
 */
free_retention_days: number | null, };
