// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlanInfo } from "./PlanInfo";

/**
 * `GET /v1/billing/plans`. Public: the pricing table is readable signed out.
 */
export type PlansResponse = { billing_enabled: boolean, 
/**
 * Paid plans only — Free is the absence of a subscription, not a product.
 */
plans: Array<PlanInfo>, };
