// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `POST /v1/catalog/playlists:search`: playlists a server's bot may queue, by name: anyone's
 * public ones, and the asker's own (whatever their visibility) when the Hub knows who asked and
 * the server may act for them, by the same trust rule as attributing a play.
 */
export type PlaylistSearchRequest = { query: string, 
/**
 * The Discord account that asked, so their own playlists count.
 */
discord_id?: string | null, 
/**
 * At most this many, the owner's first; capped by the Hub.
 */
limit: number, };
