// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlaylistVisibility } from "./PlaylistVisibility";

/**
 * Partial update for `PATCH /v1/playlists/{id}`. Every field is optional; omitted fields are left
 * unchanged.
 *
 * "Leave alone" vs. "clear" is expressed with an explicit `clear_description` flag rather than a
 * `Option<Option<String>>` + `deserialize_with = "double_option"`: a double Option round-trips
 * badly through ts-rs, which flattens it to `string | null` and loses the outer arm entirely, so
 * TypeScript callers cannot express the distinction the Rust type claims to make. A plain flag is
 * the same information in a shape both languages can actually spell.
 */
export type PlaylistPatch = { 
/**
 * New name. Rejected server-side when it trims empty.
 */
name?: string | null, 
/**
 * New description. Ignored when `clear_description` is set.
 */
description?: string | null, 
/**
 * Set the description back to NULL. Takes precedence over `description`.
 */
clear_description: boolean, visibility?: PlaylistVisibility | null, };
