// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlaylistVisibility } from "./PlaylistVisibility";

/**
 * A playlist summary (sidebar list).
 */
export type Playlist = { id: string, name: string, track_count: number, 
/**
 * User-set cover, if any. Takes precedence over `auto_cover_urls`.
 */
cover_url?: string | null, 
/**
 * Up to 4 distinct album covers from the playlist's tracks, for an auto mosaic when no
 * `cover_url` is set.
 */
auto_cover_urls: Array<string>, created_at: bigint, 
/**
 * Whether the viewer owns this playlist (false = they collaborate on someone else's).
 */
owned: boolean, 
/**
 * Whether the playlist has any collaborators.
 */
collaborative: boolean, 
/**
 * Who may see the playlist. Defaults to `Private` for payloads written before visibility existed.
 */
visibility: PlaylistVisibility, };
