// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlaylistTrackRef } from "./PlaylistTrackRef";

export type PlaylistTracksResponse = { name: string, owner_handle: string, tracks: Array<PlaylistTrackRef>, 
/**
 * Tracks on the playlist that none of the server's libraries hold.
 */
missing: number, };
