// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `POST /v1/catalog/playlists:tracks`: a playlist's tracks as the refs of this server's own
 * libraries, in playlist order. Tracks the server does not hold are counted, not returned.
 */
export type PlaylistTracksRequest = { playlist_id: string, };
