// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BucketGranularity } from "./BucketGranularity";
import type { Period } from "./Period";
import type { StatsScope } from "./StatsScope";
import type { TimeBucket } from "./TimeBucket";
import type { TopItem } from "./TopItem";

/**
 * Listening stats for one playlist, behind `GET /v1/playlists/{id}/stats`.
 *
 * Deliberately its own type rather than a widened [`EntityKind`]: a playlist is not a catalog
 * entity, and the entity path switches exhaustively over the kind on both sides.
 */
export type PlaylistStats = { id: string, period: Period, window_start: bigint, window_end: bigint, granularity: BucketGranularity, 
/**
 * Whose plays these figures cover. Echoed back so a panel can label itself honestly rather
 * than trusting the toggle it sent.
 */
scope: StatsScope, total_plays: number, total_ms_played: bigint, 
/**
 * First/last play attributed to this playlist (epoch millis). `None` if never played.
 */
first_played?: bigint | null, last_played?: bigint | null, 
/**
 * Distinct listeners in the window. Only meaningful — and only populated — for
 * `StatsScope::Global`; always `None` for `Me`.
 */
unique_listeners?: number | null, 
/**
 * Hub-wide all-time plays from the playlist's global rollup. `None` until the rollup has a row.
 */
global_plays?: bigint | null, 
/**
 * Local-calendar play trend (chronological), for a sparkline.
 */
trend: Array<TimeBucket>, 
/**
 * Most-played tracks *from this playlist* in the window.
 */
top_tracks: Array<TopItem>, 
/**
 * When playlist attribution began (epoch millis). Plays recorded before this have no playlist
 * context and can never be attributed, so the UI must state the limitation.
 */
tracking_since: bigint, };
