// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlaylistTrackRef = { library_id: string, 
/**
 * The library's own id for the track.
 */
track_ref: string, };
