// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BrowseTrack } from "./BrowseTrack";
import type { PlaylistVisibility } from "./PlaylistVisibility";
import type { PublicUser } from "./PublicUser";

/**
 * A playlist with its (playable) tracks.
 */
export type PlaylistDetail = { id: string, name: string, cover_url?: string | null, auto_cover_urls: Array<string>, tracks: Array<BrowseTrack>, 
/**
 * Whether the viewer owns this playlist.
 */
owned: boolean, 
/**
 * Whether the viewer may edit (add/remove tracks), as an owner or collaborator.
 */
can_edit: boolean, 
/**
 * Users the owner has invited to collaborate.
 */
collaborators: Array<PublicUser>, 
/**
 * The playlist's owner, resolved server-side so the header can credit and link them.
 */
owner: PublicUser, 
/**
 * Optional free-text description shown under the title.
 */
description?: string | null, 
/**
 * Who may see the playlist. Defaults to `Private` for payloads written before visibility existed.
 */
visibility: PlaylistVisibility, 
/**
 * The playlist's REAL length, counted server-side over `playlist_tracks`. Deliberately not
 * `tracks.len()`: `tracks` is filtered to what the viewer can actually play.
 */
track_count: number, 
/**
 * Sum of the durations behind `track_count` (milliseconds), on the same unfiltered basis.
 */
total_duration_ms: bigint, };
