// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A playlist the bot may queue.
 */
export type PlaylistHit = { id: string, name: string, owner_handle: string, 
/**
 * The server owner's own; otherwise it is someone's public playlist.
 */
owned: boolean, 
/**
 * Every track on it, whether or not this server holds them.
 */
track_count: number, duration_ms: bigint, };
