// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `POST /v1/catalog/playlists:search`: playlists a server's bot may queue, by name: the server
 * owner's own (whatever their visibility) and anyone's public ones.
 */
export type PlaylistSearchRequest = { query: string, 
/**
 * At most this many, the owner's first; capped by the Hub.
 */
limit: number, };
