// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the bytes the user heard came from. Stored so insights can distinguish personal
 * listening from room/relay listening.
 */
export type PlaybackSource = "local" | "own_library" | "relay" | "friend";
