// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who may see a playlist. `Unlisted` is link-only: not listed on the owner's profile, but
 * viewable by anyone who has the id.
 */
export type PlaylistVisibility = "private" | "unlisted" | "public";
