// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body of `PUT /v1/playlists/{id}/tracks/order`: the complete track order, top to bottom.
 *
 * Ids absent from the playlist are ignored; playlist tracks absent from this list keep their
 * current position.
 */
export type PlaylistTrackOrder = { track_ids: Array<string>, };
