// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `POST /v1/billing/portal`: a one-time link into the provider's customer portal, where cancelling,
 * resuming and payment methods live.
 */
export type PortalResponse = { url: string, };
