// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An artist on a user's profile "followed artists" shelf. Identity is the MBID because a followed
 * artist need not exist in this Hub's catalog.
 */
export type ProfileArtist = { artist_mbid: string, name: string, image_url?: string | null, 
/**
 * Local catalog id when the artist resolves here, so the card can link internally.
 */
artist_id?: string | null, };
