// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A profile's own colour, applied to that page only.
 */
export type ProfileAccent = { 
/**
 * A CSS colour. Already resolved: a time-varying accent is flattened, because a visitor's page
 * must not animate.
 */
primary: string, 
/**
 * Two or more stops when the owner chose a gradient; empty otherwise.
 */
gradient: Array<string>, };
