// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a profile's owner is playing right now.
 *
 * Smaller than [`FriendNowPlaying`] on purpose: that one identifies WHO, because it arrives in a
 * list of several people. A profile already knows whose it is, so repeating the handle, display
 * name and avatar in the same payload would be three fields the page cannot use.
 */
export type ProfileNowPlaying = { 
/**
 * The catalog track, when the report carried one — links the row to its page.
 */
track_id?: string | null, title: string, artist: string, image_url?: string | null, 
/**
 * When the report landed (epoch millis).
 */
started_at: bigint, };
