// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One external link on a user's profile.
 */
export type ProfileLink = { 
/**
 * Free-text kind (e.g. `bandcamp`, `website`), used to pick an icon. Unknown kinds render generically.
 */
kind: string, url: string, };
