// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Minimal public view of a user. This is what friend discovery and room listings expose.
 */
export type PublicUser = { id: string, handle: string, display_name: string, avatar_url?: string | null, };
