// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserFlair } from "./UserFlair";

/**
 * Minimal public view of a user. This is what friend discovery and room listings expose.
 */
export type PublicUser = { id: string, handle: string, display_name: string, avatar_url?: string | null, 
/**
 * How to paint this user's name, when they have that perk and have left it on. Resolved by the
 * Hub rather than sent as "their tier", so a client can never render a flair the subject is not
 * entitled to, and never has to know the tier of everyone in a list.
 */
flair?: UserFlair | null, };
