// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FriendshipStatus } from "./FriendshipStatus";
import type { Playlist } from "./Playlist";
import type { ProfileArtist } from "./ProfileArtist";
import type { ProfileLink } from "./ProfileLink";
import type { PublicUser } from "./PublicUser";
import type { RecentPlay } from "./RecentPlay";
import type { TopItem } from "./TopItem";

/**
 * A user's shareable public listening profile. Listening stats are populated only when the viewer
 * is allowed to see them (per the target's scrobble privacy); otherwise `private` is true and the
 * lists are empty.
 */
export type PublicProfile = { user: PublicUser, 
/**
 * When the account was created (epoch millis).
 */
created_at: bigint, 
/**
 * True when the viewer may not see this user's **listening activity** — `total_plays`,
 * `top_artists`, `top_tracks` and `recent` are then empty. Kept under its original name for
 * compatibility; it says nothing about the profile's other surfaces, which carry their own
 * visibility signals below.
 */
private: boolean, 
/**
 * **The whole profile is withheld** — the viewer may not see this account at all, and every
 * field below is a placeholder rather than a fact.
 *
 * Distinct from `private`, which walls only the listening activity. The two are different
 * walls with different copy: conflating them produces a page announcing "this profile is
 * private" while showing the person's bio, banner and links.
 *
 * Explicit rather than inferred. The locked shell is a zeroed DTO, and a genuinely visible
 * profile can produce a byte-identical one — a new account with default settings, no bio and
 * no followers, or ANY profile on an instance with the social layer switched off. A client
 * guessing from field shape therefore walls real profiles, which is precisely the "client
 * decides visibility" mistake the rest of this DTO is shaped to prevent.
 */
hidden: boolean, total_plays: number, top_artists: Array<TopItem>, top_tracks: Array<TopItem>, recent: Array<RecentPlay>, 
/**
 * Free-text profile bio.
 */
bio?: string | null, 
/**
 * Resolved banner image URL (the Hub image endpoint), when one is set.
 */
banner_url?: string | null, links: Array<ProfileLink>, follower_count: number, following_count: number, playlist_count: number, 
/**
 * The viewer follows this account.
 */
viewer_follows: boolean, 
/**
 * This account follows the viewer.
 */
follows_viewer: boolean, 
/**
 * Friendship edge between viewer and this account, when one exists.
 */
friendship?: FriendshipStatus | null, 
/**
 * Whether the viewer may follow this account (false when already following, when it is their
 * own profile, or when the target is not open to follows).
 */
can_follow: boolean, 
/**
 * Whether the viewer may open the followers list.
 */
followers_visible: boolean, 
/**
 * Whether the viewer may open the following list.
 */
following_visible: boolean, 
/**
 * The user's playlists. **The `Option` IS the visibility signal**: `None` means the viewer may
 * not see this surface at all (render nothing), `Some([])` means it is visible and empty
 * (render the empty state). The client never decides visibility — the server has already
 * applied `playlists_visibility` and each playlist's own `PlaylistVisibility`.
 */
playlists?: Array<Playlist> | null, 
/**
 * The user's followed artists, with the same `None` = not visible / `Some([])` = visible and
 * empty contract as `playlists`.
 */
followed_artists?: Array<ProfileArtist> | null, };
