// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Listener-selectable quality tier. `Original` is the default and is byte-for-byte lossless;
 * lower tiers are produced by on-the-fly transcode and may be auto-selected when
 * `auto_downgrade` is enabled and bandwidth can't sustain the current tier.
 */
export type QualityProfile = "original" | "high" | "normal" | "data_saver";
