// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QualityProfile } from "./QualityProfile";

/**
 * Per-network-class playback preference, persisted client-side and synced to the Hub.
 */
export type QualityPreferences = { wifi: QualityProfile, cellular: QualityProfile, 
/**
 * Step the tier down automatically when buffer health degrades (and back up on recovery).
 */
auto_downgrade: boolean, };
