// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrackFingerprint } from "./TrackFingerprint";

/**
 * A queued track waiting to be played.
 */
export type QueueItem = { queue_id: string, fingerprint: TrackFingerprint, title: string, artist: string, added_by: string, votes: number, };
