// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChartEntry } from "./ChartEntry";

/**
 * A ranked item whose position changed between adjacent reporting windows.
 */
export type RankMove = { item: ChartEntry, delta?: number | null, };
