// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChartEntry } from "./ChartEntry";
import type { EntityKind } from "./EntityKind";
import type { Period } from "./Period";
import type { RankMove } from "./RankMove";

/**
 * Current-window chart movement compared with the immediately preceding window.
 */
export type RankMovers = { kind: EntityKind, period: Period, climbers: Array<RankMove>, fallers: Array<RankMove>, newcomers: Array<ChartEntry>, };
