// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lightweight "recently played" feed item for the home view.
 */
export type RecentPlay = { 
/**
 * The play event's idempotency id. Always present, so it is the stable list key.
 */
event_id: string, 
/**
 * Resolved catalog track id, so the row can link to the track. `None` when the scrobble never
 * matched the catalog — which is why this cannot double as the list key.
 */
track_id?: string | null, 
/**
 * Resolved primary artist id, when the scrobble matched the catalog.
 */
artist_id?: string | null, 
/**
 * Resolved album id, when the scrobble matched the catalog.
 */
album_id?: string | null, title: string, artist: string, 
/**
 * Catalog cover resolved like history rows: track cover first, then album cover, through the
 * Hub image endpoint.
 */
image_url?: string | null, played_at: bigint, };
