// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What kind of entity a "jump back in" card points at.
 */
export type RecentKind = "album" | "artist" | "playlist";
