// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecentKind } from "./RecentKind";

/**
 * One "Jump back in" card: a recently played album/artist or one of the user's playlists.
 */
export type RecentItem = { kind: RecentKind, id: string, 
/**
 * MusicBrainz id of the album's release-group / the artist, when known. Carried so a menu on a
 * "Jump back in" card can link straight into the Manager instead of falling back to a name
 * search — the source rows already have it. Always None for playlists.
 */
mbid?: string | null, name: string, 
/**
 * Secondary line (e.g. the album's artist), when there is one.
 */
subtitle?: string | null, image_url?: string | null, };
