// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body for `POST /v1/auth/refresh`.
 */
export type RefreshRequest = { refresh_token: string, };
