// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Global account registration payload.
 */
export type RegisterRequest = { 
/**
 * Unique, URL-safe handle (e.g. `nina`). Validated server-side.
 */
handle: string, email: string, password: string, display_name: string, };
