// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QualityProfile } from "./QualityProfile";

/**
 * Request from a client to its **own** library to relay a track it does not own from the DJ's
 * library (the "Hybrid Relay" fallback).
 */
export type RelayRequest = { 
/**
 * Reachable base URL of the DJ's library (from the Hub directory).
 */
dj_endpoint: string, 
/**
 * TLS fingerprint to pin on the relay pull.
 */
dj_tls_fingerprint: string, 
/**
 * Track to fetch on the DJ's side.
 */
track_id: string, 
/**
 * Hub-minted relay capability token (audience = DJ library).
 */
relay_token: string, 
/**
 * Room context.
 */
room_id: string, profile: QualityProfile, };
