// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What object storage holds, when the Hub can see it.
 */
export type RemoteStatus = { 
/**
 * The listing succeeded. False means the credentials or the bucket are wrong, and the local
 * list is still correct — a remote that cannot be read must not make the whole tab an error.
 */
reachable: boolean, 
/**
 * Why not, when unreachable.
 */
problem?: string | null, 
/**
 * Archives seen (the erasure ledger and anything else in the bucket are excluded).
 */
archives: bigint, 
/**
 * Their total size. Current versions only; superseded ones are not counted.
 */
total_bytes: bigint, };
