// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What object storage holds, when the Hub can see it.
 */
export type RemoteStatus = { 
/**
 * The listing succeeded. False means the credentials or the bucket are wrong, and the local
 * list is still correct — a remote that cannot be read must not make the whole tab an error.
 */
reachable: boolean, 
/**
 * Why not, when unreachable.
 */
problem?: string | null, 
/**
 * Archives seen (the erasure ledger and anything else in the bucket are excluded).
 */
archives: bigint, 
/**
 * Their total size. Current versions only; superseded ones are not counted.
 */
total_bytes: bigint, 
/**
 * Storage price used for [`Self::monthly_cost_usd`], per GB per month.
 *
 * Returned alongside the figure so the arithmetic is inspectable rather than magic, and so a
 * reader can tell a wrong total from a wrong rate.
 */
rate_per_gb_usd: number, 
/**
 * **An estimate.** Storage only, at the rate above, on current versions.
 *
 * It will not match an invoice: B2 bills byte-hours rather than a month-end snapshot, egress
 * and transaction classes are excluded, and superseded versions of the erasure ledger occupy
 * real bytes this figure does not count. Close enough to answer "is this about to get
 * expensive", not close enough to reconcile against a bill.
 */
monthly_cost_usd: number, };
