// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One user report awaiting (or past) moderation.
 */
export type ReportRow = { id: string, reporter_handle?: string | null, target_handle?: string | null, reason: string, details?: string | null, status: string, created_at_ms: bigint, };
