// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A listener the server may attribute plays to.
 */
export type ResolvedListener = { discord_id: string, user_id: string, handle: string, display_name: string, avatar_url?: string | null, 
/**
 * The server's owner, as opposed to a share holder.
 */
is_owner: boolean, };
