// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `POST /v1/directory/listeners:resolve`: the Discord ids in a voice channel.
 */
export type ResolveListenersRequest = { discord_ids: Array<string>, };
