// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The Hub's ids for one of the library's tracks, for deep links.
 */
export type ResolvedTrack = { track_ref: string, track_id: string, album_id?: string | null, artist_id?: string | null, };
