// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `POST /v1/catalog/resolve-tracks`: a library's own track ids, as it sent them in catalog sync.
 */
export type ResolveTracksRequest = { 
/**
 * The Hub's id for the library (the one catalog sync uses).
 */
library_id: string, track_refs: Array<string>, };
