// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The resource a capability token is scoped to.
 */
export type ResourceRef = { "kind": "track", track_id: string, } | { "kind": "album", album_id: string, } | { "kind": "library", library_id: string, };
