// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResolvedListener } from "./ResolvedListener";

/**
 * Only the listeners who passed the trust rule and have not opted out; the rest are absent.
 */
export type ResolveListenersResponse = { listeners: Array<ResolvedListener>, };
