// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServerEndpoint } from "./ServerEndpoint";

/**
 * Result of resolving a server before initiating a direct stream.
 */
export type ResolvedServer = { endpoint: ServerEndpoint, 
/**
 * True if the Hub also issued a capability token alongside this resolution.
 */
authorized: boolean, };
