// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a completed restore did.
 */
export type RestoreReport = { name: string, 
/**
 * Name of the automatic pre-restore dump, so the previous state is recoverable. Written before
 * anything is dropped; if this is `None` the restore did not proceed.
 */
safety_dump?: string | null, 
/**
 * Accounts re-erased by the ledger replay after the data went in.
 */
re_erased: bigint, 
/**
 * Ledger rows asserted afterwards, so the NEXT restore still knows about all of them.
 */
ledger_entries: bigint, duration_ms: bigint, };
