// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NowPlaying } from "./NowPlaying";
import type { PublicUser } from "./PublicUser";
import type { QueueItem } from "./QueueItem";

/**
 * Full room snapshot (sent on join, then kept current via deltas).
 */
export type RoomState = { room_id: string, title: string, current_dj: string | null, listeners: Array<PublicUser>, now_playing: NowPlaying | null, queue: Array<QueueItem>, };
