// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A freshly rotated server API key (`POST /v1/servers/{server_id}/rotate-key`). The previous key
 * stops authenticating immediately, so the library has to be re-paired or reconfigured with this
 * one.
 */
export type RotatedServerKey = { server_id: string, server_api_key: string, };
