// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who may see a user's listening activity (recent-scrobble feed, top artists, taste
 * compatibility). Defaults to `Friends` so sharing is opt-in beyond one's friends.
 *
 * **This IS the listening-history / top-artists visibility control** — enforced in
 * `backend/src/api/v1/insights.rs`. Do not add a separate `history_visibility` knob.
 *
 * The duplication with [`Audience`] is DELIBERATE and the two must not be merged: this enum's TS
 * binding and its `scrobble_privacy` key in the stored `user_settings` JSONB payload are
 * load-bearing across the frontend and in SQL (`payload->>'scrobble_privacy'`).
 */
export type ScrobblePrivacy = "public" | "friends" | "private";
