// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ingestion result. `accepted` + `duplicates` should equal the batch size.
 */
export type ScrobbleBatchResponse = { accepted: number, 
/**
 * Events deduped by `event_id` (already ingested).
 */
duplicates: number, 
/**
 * Event ids rejected as malformed, if any.
 */
rejected: Array<string>, };
