// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An owner's correction to one of their own listening events
 * (`PATCH /v1/scrobbles/{event_id}`, a Super-Sonic capability).
 *
 * At least one field must be present. Re-attributing (`track_id`) rewrites the event's canonical
 * ids AND its denormalized display text together; moving it (`started_at`) may relocate the row
 * to a different monthly partition. Either way the rollups are repaired by exact recompute.
 */
export type ScrobbleEdit = { 
/**
 * Re-attribute the play to this track (must be in a library the caller can access).
 */
track_id?: string | null, 
/**
 * Move the play to this start time (epoch millis, bounded to [2000-01-01, now + 5 min]).
 */
started_at?: bigint | null, };
