// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ListeningEvent } from "./ListeningEvent";

/**
 * A batch flush of buffered events (`POST /v1/scrobbles:batch`). Clients buffer offline and
 * flush on reconnect.
 */
export type ScrobbleBatch = { events: Array<ListeningEvent>, };
