// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BrowseAlbum } from "./BrowseAlbum";
import type { BrowseArtist } from "./BrowseArtist";
import type { BrowseTrack } from "./BrowseTrack";
import type { LabelSummary } from "./LabelSummary";

/**
 * Global catalog search results.
 */
export type SearchResults = { artists: Array<BrowseArtist>, albums: Array<BrowseAlbum>, tracks: Array<BrowseTrack>, labels: Array<LabelSummary>, };
