// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A library server's current reachability record in the Hub directory.
 */
export type ServerEndpoint = { server_id: string, owner_id: string, 
/**
 * Reachable base URL, e.g. `https://music.example.com:8443` or `https://203.0.113.7:8443`.
 */
endpoint: string, 
/**
 * SHA-256 of the server's TLS leaf certificate (hex). Clients **pin** this, making
 * self-signed certs safe against MITM.
 */
tls_fingerprint: string, online: boolean, last_heartbeat: bigint, };
