// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who owns a library server, as the Hub tells the server itself (`GET /v1/directory/me`).
 * The library's Discord bots treat the owner as an implicit bot owner, through the Discord
 * account the owner linked to Chordia, if any.
 */
export type ServerOwner = { server_id: string, owner_id: string, handle: string, display_name: string, discord_id?: string | null, };
