// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NowPlaying } from "./NowPlaying";
import type { PublicUser } from "./PublicUser";
import type { QueueItem } from "./QueueItem";
import type { RoomState } from "./RoomState";

/**
 * Messages the `dj` service broadcasts to room clients.
 */
export type ServerMessage = { "type": "snapshot", state: RoomState, } | { "type": "now_playing", now_playing: NowPlaying, } | { "type": "queue_updated", queue: Array<QueueItem>, } | { "type": "listener_joined", user: PublicUser, } | { "type": "listener_left", user_id: string, } | { "type": "dj_changed", dj_user_id: string | null, } | { "type": "chat", from: string, body: string, at: bigint, } | { "type": "pong", client_time: bigint, server_time: bigint, } | { "type": "error", message: string, };
