// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One active login session ("device"), as shown in account settings.
 */
export type SessionInfo = { session_id: string, 
/**
 * When the session began (epoch millis).
 */
created_at: bigint, 
/**
 * Last time the session refreshed (epoch millis).
 */
last_used_at: bigint, 
/**
 * Raw User-Agent captured at last refresh, for a human-readable device label.
 */
user_agent?: string | null, 
/**
 * True for the session making this request.
 */
current: boolean, };
