// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionLevel } from "./PermissionLevel";

/**
 * Create or update a share (Hub-side, requires an accepted friendship).
 */
export type ShareRequest = { library_id: string, grantee_id: string, permission_level: PermissionLevel, };
