// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A friend's live stream from one of your libraries (owner-facing; respects the listener's
 * scrobble privacy — private listeners simply don't appear).
 */
export type ShareNowStreaming = { title: string, artist: string, image_url?: string | null, started_at: bigint, };
