// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A user who shares listening taste with the caller (for the "similar listeners" surface).
 */
export type SimilarUser = { id: string, handle: string, display_name: string, avatar_url?: string | null, 
/**
 * Count of artists both the caller and this user have played.
 */
shared_artists: number, };
