// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SmartCondition } from "./SmartCondition";
import type { SmartMatch } from "./SmartMatch";
import type { SmartSort } from "./SmartSort";

/**
 * The full rule set for a smart playlist.
 */
export type SmartRules = { match_mode: SmartMatch, conditions: Array<SmartCondition>, sort: SmartSort, 
/**
 * Max tracks to resolve (clamped server-side). `None` = a sensible default.
 */
limit?: number | null, };
