// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BrowseTrack } from "./BrowseTrack";

/**
 * `POST /v1/smart-playlists/preview`: what a rule set would produce, without saving it.
 */
export type SmartPreview = { 
/**
 * Matching tracks, ignoring [`SmartRules::limit`] so the builder can warn that a limit is
 * cutting the result down.
 */
count: number, 
/**
 * The count stopped at an internal ceiling, so it is a floor rather than an exact number.
 */
count_capped: boolean, 
/**
 * The first few matches in sort order.
 */
sample: Array<BrowseTrack>, };
