// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SmartField } from "./SmartField";
import type { SmartOp } from "./SmartOp";
import type { SmartPeriod } from "./SmartPeriod";

/**
 * One rule: `<field> <op> <value>`. `value` is always a string; the Hub parses it per field.
 */
export type SmartCondition = { field: SmartField, op: SmartOp, value: string, 
/**
 * Every value this rule accepts, matched as OR: `artist is A, B, C`. Empty means the rule is
 * the single `value` above, which is how every rule written before this field existed reads.
 *
 * `value` is kept in sync with the first entry rather than being emptied, so a reader that
 * predates this field still resolves the rule to something sensible instead of to nothing.
 * Only the text fields use it; a numeric or date rule ignores it.
 */
values?: Array<string>, 
/**
 * Upper bound for [`SmartOp::Between`]; ignored by every other operator.
 */
value2?: string | null, 
/**
 * Scopes [`SmartField::MyPlays`] to a window. `None` means all time.
 */
period?: SmartPeriod | null, };
