// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Sort order for the resolved tracks.
 */
export type SmartSort = "title" | "plays" | "random";
