// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What one refresh actually changed. Returned by the manual refresh so the button can say
 * something true — including "nothing changed", which is a result and not a failure.
 */
export type SmartRefreshResult = { 
/**
 * Tracks now in the playlist that were not in the previous snapshot.
 */
added: number, 
/**
 * Tracks that were in the previous snapshot and no longer match.
 */
removed: number, 
/**
 * Size of the new snapshot.
 */
total: number, refreshed_at: bigint, };
