// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SmartField } from "./SmartField";
import type { SmartOp } from "./SmartOp";

/**
 * One rule: `<field> <op> <value>`. `value` is always a string; the Hub parses it per field.
 */
export type SmartCondition = { field: SmartField, op: SmartOp, value: string, };
