// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A window of listening history, for [`SmartField::MyPlays`] and period-scoped sorting.
 *
 * Calendar and rolling windows are separate variants rather than a day count because they answer
 * different questions and read from different places: a calendar month or year is served by the
 * monthly rollup tables, while a rolling window has to scan the events themselves.
 */
export type SmartPeriod = { "kind": "month", month: string, } | { "kind": "year", year: number, } | { "kind": "rolling", days: number, };
