// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SmartCondition } from "./SmartCondition";
import type { SmartMatch } from "./SmartMatch";
import type { SmartPeriod } from "./SmartPeriod";
import type { SmartSort } from "./SmartSort";
import type { SmartSortDir } from "./SmartSortDir";

/**
 * The full rule set for a smart playlist.
 *
 * Every field added after the first version is `#[serde(default)]`, and the rules are stored as
 * JSONB — so a playlist saved by an older client still deserializes, unchanged, forever.
 */
export type SmartRules = { match_mode: SmartMatch, conditions: Array<SmartCondition>, sort: SmartSort, 
/**
 * Max tracks to resolve (clamped server-side). `None` = a sensible default.
 */
limit?: number | null, 
/**
 * The window [`SmartSort::MyPlaysInPeriod`] ranks within. Required by that sort and ignored by
 * every other.
 */
sort_period?: SmartPeriod | null, sort_dir?: SmartSortDir | null, };
