// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BrowseTrack } from "./BrowseTrack";
import type { SmartRules } from "./SmartRules";

/**
 * A smart playlist with its materialised tracks.
 */
export type SmartPlaylistDetail = { id: string, name: string, rules: SmartRules, tracks: Array<BrowseTrack>, 
/**
 * See [`SmartPlaylist::cover_url`].
 */
cover_url?: string | null, 
/**
 * See [`SmartPlaylist::auto_cover_urls`].
 */
auto_cover_urls: Array<string>, 
/**
 * Minutes between automatic refreshes; [`SMART_REFRESH_NEVER`] (`0`) = manual only.
 */
refresh_interval_minutes: number, 
/**
 * When the snapshot was last successfully rebuilt. `None` = never resolved yet.
 */
refreshed_at: bigint | null, };
