// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SmartField } from "./SmartField";
import type { SmartOp } from "./SmartOp";
import type { SmartPeriod } from "./SmartPeriod";

/**
 * One rule: `<field> <op> <value>`. `value` is always a string; the Hub parses it per field.
 */
export type SmartCondition = { field: SmartField, op: SmartOp, value: string, 
/**
 * Upper bound for [`SmartOp::Between`]; ignored by every other operator.
 */
value2?: string | null, 
/**
 * Scopes [`SmartField::MyPlays`] to a window. `None` means all time.
 */
period?: SmartPeriod | null, };
