// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The track attribute a condition tests.
 */
export type SmartField = "artist" | "title" | "album" | "genre" | "year" | "plays" | "liked";
