// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a condition compares the field to its value.
 */
export type SmartOp = "contains" | "equals" | "gte" | "lte" | "is";
