// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Sort direction. `None` on [`SmartRules::sort_dir`] means each sort's natural direction: A-Z for
 * title, largest or most recent first for everything else.
 */
export type SmartSortDir = "asc" | "desc";
