// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SmartRules } from "./SmartRules";

/**
 * A smart playlist summary.
 */
export type SmartPlaylist = { id: string, name: string, created_at: bigint, rules: SmartRules, 
/**
 * A Phosphor icon slug, or `emoji:` + a literal emoji — the same encoding libraries use. `None`
 * keeps the funnel that every smart playlist used to be stuck with.
 */
icon?: string | null, 
/**
 * Minutes between automatic refreshes; [`SMART_REFRESH_NEVER`] (`0`) = manual only.
 */
refresh_interval_minutes: number, 
/**
 * When the snapshot was last successfully rebuilt. `None` = never resolved yet. A FAILED
 * refresh does not move this, so a stale stamp is a visible symptom rather than a lie.
 */
refreshed_at: bigint | null, 
/**
 * Tracks in the current snapshot, without hydrating them.
 */
track_count: number, };
