// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BrowseTrack } from "./BrowseTrack";
import type { SmartRules } from "./SmartRules";

/**
 * A smart playlist with its currently-resolved tracks.
 */
export type SmartPlaylistDetail = { id: string, name: string, rules: SmartRules, tracks: Array<BrowseTrack>, };
