// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SmartRules } from "./SmartRules";

/**
 * A smart playlist summary.
 */
export type SmartPlaylist = { id: string, name: string, created_at: bigint, rules: SmartRules, };
