// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A staff member's role, shown on their badge so moderation actions have a face.
 */
export type StaffRole = "support" | "moderator" | "admin";
