// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a station was seeded from. A genre seed is a slug, not an id — see [`Station::seed_id`].
 */
export type StationKind = "artist" | "track" | "album" | "genre" | "playlist";
