// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which way a station faces.
 *
 * **Not a label on the same list.** `Radio` points outward: it weights novelty, admits tracks the
 * listener has never played, and is endless. `Mix` points inward: it draws only from artists the
 * listener already plays plus their liked tracks, and is finite and stable for the day. The two are
 * the same machinery with the affinity term's SIGN flipped, which is the whole distinction.
 */
export type StationFlavour = "radio" | "mix";
