// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whose listening an entity page is reporting on.
 */
export type StatsScope = "me" | "global";
