// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BrowseTrack } from "./BrowseTrack";
import type { StationFlavour } from "./StationFlavour";
import type { StationKind } from "./StationKind";

export type Station = { kind: StationKind, 
/**
 * The seed's identifier. A **String**, not a Uuid: a genre station is seeded by a slug.
 */
seed_id: string, 
/**
 * The seed's own name, unformatted.
 *
 * Load-bearing rather than redundant with `title`. The server used to hard-code English titles
 * (`format!("{name} Mix")`), which no amount of client-side i18n could undo. Handing back the
 * raw name lets the client compose the title in the listener's language; `title` remains the
 * server's fallback for any consumer that will not.
 */
seed_name: string, title: string, subtitle: string, image_url?: string | null, flavour: StationFlavour, tracks: Array<BrowseTrack>, 
/**
 * Opaque continuation token, or `None` when the station is finite.
 *
 * Stateless by construction: it encodes the day and an offset, so `/more` rebuilds the same
 * weave rather than reading a server-side session, and a retried request is idempotent.
 */
next_cursor?: string | null, };
