// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QualityProfile } from "./QualityProfile";

/**
 * Query params for the stream endpoint (`GET /v1/stream/{track_id}`). The `Range` header drives
 * byte positioning; this only selects the tier.
 */
export type StreamQuery = { profile: QualityProfile, 
/**
 * Set by a client that is keeping a copy rather than playing the bytes through. It is the
 * only way the server can tell the two apart - the HTTP request is otherwise identical - so a
 * stream-only capability (`PermissionLevel::Read`) is refused when it is set. An honest flag
 * from our own clients, backed by the UI refusing the action for such a share; the share tier
 * is a courtesy boundary between friends, not a DRM claim.
 *
 * Spelled `download=true` on the wire, never `download=1`: this is a `bool` and the server
 * deserializes the query with `serde_urlencoded`, which accepts only `true`/`false` and
 * fails the *whole* query on anything else - so `1` does not mean false, it means 400.
 */
download: boolean, };
