// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One consecutive run of active listening days.
 */
export type Streak = { 
/**
 * First local calendar day in the run (`YYYY-MM-DD`).
 */
start_day: string, 
/**
 * Last local calendar day in the run (`YYYY-MM-DD`).
 */
end_day: string, days: number, plays: number, 
/**
 * True when the run reaches today or yesterday in the requested timezone.
 */
active: boolean, };
