// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QualityProfile } from "./QualityProfile";

/**
 * Query params for the stream endpoint (`GET /v1/stream/{track_id}`). The `Range` header drives
 * byte positioning; this only selects the tier.
 */
export type StreamQuery = { profile: QualityProfile, };
