// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One field a user proposes a new value for. `value_text` carries name/bio/genres (genres as a
 * comma-separated list); `value_image_hash` carries an uploaded image/banner hash (from `POST
 * /v1/images`). Exactly one is set per `field`.
 */
export type SuggestionFieldInput = { 
/**
 * `image` | `banner` | `name` | `bio` | `genres`.
 */
field: string, value_text?: string | null, value_image_hash?: string | null, };
