// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One field a user proposes a new value for. `value_text` carries name/bio/genres (genres as a
 * comma-separated list); `value_image_hash` carries an uploaded image/banner hash (from `POST
 * /v1/images`). Exactly one is set per `field`.
 */
export type SuggestionFieldInput = { 
/**
 * What is being proposed, keyed by CONCEPT rather than by column so one review queue serves
 * every entity kind: `name` is an artist's name and an album's or track's title, `image` is the
 * primary artwork. Which keys are accepted depends on `MetadataSuggestionInput::entity_type` —
 * artists take `image`/`banner`/`name`/`bio`/`genres`, albums take
 * `image`/`name`/`genres`/`year`/`release_date`/`label`/`album_type`, tracks take `name`.
 */
field: string, value_text?: string | null, value_image_hash?: string | null, };
