// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One track in a catalog sync push. Carries everything the Hub needs to materialize canonical
 * artist/album/track rows and to associate the track with the originating library.
 */
export type SyncTrack = { title: string, artist: string, artist_normalized: string, 
/**
 * MusicBrainz id of the PRIMARY credited artist, from the file's `MusicBrainz Artist Id` tag.
 *
 * Artist identity used to cross this wire as name strings alone, so the Hub could only match on
 * a name — and a name is not an identity. An album tagged with an artist's former name
 * normalizes to something the current row does not equal, so ingest missed it and minted a
 * duplicate; two different artists sharing a name collided the other way. The library had this
 * id all along (`artists.mbid`, from `metadata.rs`) and already ships it over a DIFFERENT wire
 * (`UpgradeProposal.artist_mbid`), so the omission here was a gap, not a data limitation.
 *
 * Optional because plenty of files carry no MusicBrainz tags at all; when it is absent the Hub
 * falls back to the name matching it has always done.
 */
artist_mbid?: string | null, album?: string | null, album_normalized?: string | null, album_artist?: string | null, track_no: number | null, disc_no: number | null, year: number | null, genre?: string | null, duration_ms: number, 
/**
 * The library's own track id, used by the player to build the stream URL.
 */
track_ref: string, 
/**
 * SHA-256 of the file bytes, the Hub's per-library track identity key.
 */
content_hash: string, recording_mbid?: string | null, release_mbid?: string | null, isrc?: string | null, 
/**
 * SHA-256 of the embedded cover art, if any. Bytes are uploaded separately (see
 * [`CatalogSyncResponse::missing_covers`]).
 */
cover_hash?: string | null, 
/**
 * Edition qualifier ("Deluxe", "Special Edition", …) when this track comes from a deluxe/special
 * edition that folds into the base album. `None` for the standard edition.
 */
edition?: string | null, 
/**
 * Content advisory from the file's iTunes/ID3 rating tag: `"explicit"` or `"clean"`; `None` when
 * unrated. Drives the EXPLICIT badge.
 */
advisory?: string | null, };
