// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One credit as a library parsed it, on its way to the Hub inside a catalog sync.
 *
 * Flat `(name, role)` like [`Credit`], and without a source: the wire it arrives on *is* the
 * source. No `artist_id` either — a library has no opinion about the Hub's artist ids.
 */
export type SyncCredit = { name: string, role: string, is_org: boolean, };
