// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DecadeSplit } from "./DecadeSplit";
import type { DiscoveredTogether } from "./DiscoveredTogether";
import type { HourSplit } from "./HourSplit";
import type { TopItem } from "./TopItem";

/**
 * The paid deep-dive behind a compatibility score: what two listeners share, when they both
 * listen, and what they found at the same time. Every figure is bounded by each side's OWN
 * retention window — a paid viewer buys no reach into a free friend's hidden history.
 */
export type TasteSummary = { 
/**
 * Albums both have played, ranked by the smaller of the two play counts (`plays` carries that
 * shared strength), top 10.
 */
shared_albums: Array<TopItem>, 
/**
 * Tracks both have played, ranked and capped like `shared_albums`.
 */
shared_tracks: Array<TopItem>, 
/**
 * Album genres both have played. `id` is a stable hash of the genre name (genres aren't
 * catalog entities) and `image_url` is always absent.
 */
shared_genres: Array<TopItem>, 
/**
 * Album-release decades, one entry per decade on a continuous axis from the earliest decade
 * either side has played through the latest.
 */
decades: Array<DecadeSplit>, 
/**
 * Histogram intersection (0.0 to 1.0) of the two decade distributions: 1.0 means the same
 * era shares, 0.0 means no overlap at all. 0.0 when either side has no dated plays.
 */
era_overlap: number, 
/**
 * Plays by local hour of day over the trailing 90 days, exactly 24 entries (index = hour).
 * Each side's hours are measured in their own timezone — the comparison is "when in your day
 * do you each listen", not "are you awake at the same instant".
 */
hours: Array<HourSplit>, 
/**
 * Histogram intersection (0.0 to 1.0) of the two hour-of-day distributions.
 */
time_overlap: number, 
/**
 * Artists whose first listen (week-grained) happened in the same week for both sides, with at
 * least 5 plays each, strongest shared interest first, top 5.
 */
discovered_together: Array<DiscoveredTogether>, };
