// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One bucket in a time series of listening activity.
 */
export type TimeBucket = { 
/**
 * Inclusive start of the bucket (epoch millis, truncated in the requested timezone).
 */
start: bigint, plays: number, ms_played: bigint, };
