// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Issued token pair. The refresh token is opaque (server-side rotation); the access token is a
 * JWT verifiable against the Hub JWKS.
 */
export type TokenPair = { access_token: string, refresh_token: string, access_expires_at: bigint, };
