// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One ranked entry in a top-N list.
 */
export type TopItem = { 
/**
 * Catalog id of the artist/track/album.
 */
id: string, name: string, plays: number, ms_played: bigint, image_url?: string | null, };
