// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreditGroup } from "./CreditGroup";

/**
 * Response of `GET /v1/tracks/{id}/credits`.
 */
export type TrackCredits = { track_id: string, groups: Array<CreditGroup>, };
