// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TrackOverrideInput = { title?: string | null, artist?: string | null, album?: string | null, track_no?: number | null, disc_no?: number | null, genre?: string | null, cover_hash?: string | null, override_main: boolean, };
