// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Layered identity for a recording, from strongest to weakest. Lets the same song match across
 * different files/encodings during own-copy lookup in DJ rooms.
 */
export type TrackFingerprint = { 
/**
 * AcoustID. A robust acoustic fingerprint that survives re-encoding. Preferred match.
 */
acoustid?: string | null, 
/**
 * MusicBrainz Recording ID.
 */
recording_mbid?: string | null, 
/**
 * SHA-256 of the raw file bytes (hex). Used for exact-file matching and a bit-perfect integrity check.
 */
content_hash: string, 
/**
 * Normalized metadata for the fuzzy fallback tuple.
 */
artist_norm: string, title_norm: string, album_norm?: string | null, duration_ms: number, };
