// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioProperties } from "./AudioProperties";
import type { TrackFingerprint } from "./TrackFingerprint";

/**
 * A track DTO as served by a library's catalog API.
 */
export type Track = { id: string, library_id: string, title: string, 
/**
 * Track artist (may differ from album artist on compilations).
 */
artist: string, 
/**
 * Album/compilation artist tag, if present.
 */
album_artist?: string | null, album?: string | null, 
/**
 * Release year extracted from tags.
 */
year: number | null, genre?: string | null, track_no: number | null, disc_no: number | null, 
/**
 * Playback duration in milliseconds.
 */
duration_ms: number, audio: AudioProperties, fingerprint: TrackFingerprint, };
