// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One marker stripped from a title.
 *
 * Ordered by how much it changes the recording: the first few are genuinely different performances
 * and the last few describe the release a track was on. That ordering is what the client renders
 * in, so the badge that matters most is the one nearest the title.
 */
export type TrackVariant = "live" | "acoustic" | "instrumental" | "remix" | "demo" | "cover" | "karaoke" | "extended" | "radio_edit" | "single_version" | "remaster" | "bonus" | "deluxe";
