// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Concrete encoding parameters a non-`Original` tier maps to (server transcode target).
 */
export type TranscodeTarget = { codec: string, bitrate_kbps: number, };
