// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BrowseAlbum } from "./BrowseAlbum";
import type { BrowseArtist } from "./BrowseArtist";
import type { BrowseTrack } from "./BrowseTrack";

/**
 * Globally trending content over a recent window (by distinct-listener count, then plays).
 */
export type Trending = { artists: Array<BrowseArtist>, albums: Array<BrowseAlbum>, tracks: Array<BrowseTrack>, };
