// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What an admin is changing about the deployment itself. Omitted fields are left alone.
 */
export type UpdateInstanceSettings = { 
/**
 * A preset name or a `#rrggbb`. Explicit `null` clears it and restores the app's own default,
 * which is why this is a nested Option rather than a plain one — "leave it alone" and "there
 * should not be one" are different instructions.
 */
accent?: string | null | null, };
