// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProfileLink } from "./ProfileLink";

/**
 * Profile fields the user can edit. Omitted fields are left unchanged.
 */
export type UpdateProfile = { display_name?: string | null, avatar_url?: string | null, 
/**
 * New unique handle. Validated server-side; omitted leaves the handle unchanged.
 */
handle?: string | null, 
/**
 * Short free-text profile bio.
 */
bio?: string | null, 
/**
 * Content hash of an uploaded banner image (from the Hub image endpoint), not a URL.
 */
banner_hash?: string | null, 
/**
 * Full replacement list of profile links. Omitted leaves the existing links unchanged; an
 * empty vec clears them.
 */
links?: Array<ProfileLink> | null, };
