// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One album the library's quality-upgrade sweep proposes re-acquiring in better quality
 * (currently all-lossy on disk). The Hub resolves it to a release-group and queues an
 * `origin="upgrade"` job for the library owner.
 */
export type UpgradeProposal = { library_id: string, album_title: string, artist?: string | null, artist_mbid?: string | null, release_mbid?: string | null, 
/**
 * Human label of what's owned now (e.g. "MP3"), for the queue display.
 */
current_quality?: string | null, };
