// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UpgradeProposal } from "./UpgradeProposal";

/**
 * Body of `POST /v1/manager/upgrades` — the library's periodic upgrade-sweep report.
 */
export type UpgradeProposals = { proposals: Array<UpgradeProposal>, };
