// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Audience } from "./Audience";
import type { EqConfig } from "./EqConfig";
import type { EqPreset } from "./EqPreset";
import type { QualityProfile } from "./QualityProfile";
import type { ScrobblePrivacy } from "./ScrobblePrivacy";

/**
 * Per-user application preferences. Every field has a default so older/partial blobs still parse.
 */
export type UserSettings = { 
/**
 * Listener-selected quality tier (the streaming ceiling). Serializes as `original`, `high`,
 * `normal`, or `data_saver`.
 */
streaming_quality: QualityProfile, normalize_volume: boolean, 
/**
 * Whether listens are scrobbled to the Hub.
 */
scrobble: boolean, 
/**
 * Who can see this user's listening activity in social insights.
 */
scrobble_privacy: ScrobblePrivacy, 
/**
 * Whether to receive transactional email notifications (e.g. a friend request). Default on.
 */
email_notifications: boolean, 
/**
 * Accent preset name, hue-ordered: `crimson`, `ember`, `amber`, `lime`, `green`, `teal`,
 * `blue`, `indigo`, `purple`, `magenta`, or `pink` (the default). An unrecognized value is
 * used verbatim as a CSS colour.
 */
accent: string, 
/**
 * Where the app opens by default: `app` or `library`.
 */
default_surface: string, 
/**
 * Preferred UI + email language as a locale code (e.g. `en`, `es`). Empty = follow the
 * request's `Accept-Language`. Drives server-originated text (errors, emails) and the client
 * UI; the frontend also mirrors it into the `chordia_locale` cookie so SSR's first paint agrees.
 */
locale: string, 
/**
 * IANA timezone used for calendar-based listening insights. Empty = follow the client.
 */
timezone: string, autoplay: boolean, 
/**
 * How many upcoming queue tracks to prefetch in the background for seamless, gap-free
 * playback. `0` disables prefetch; clamped client-side. Prefetched audio outside the window is
 * evicted as the queue advances.
 */
preload_count: number, 
/**
 * Overlap-crossfade duration in seconds between consecutive tracks (`0` = off, the default, so
 * tracks change with the normal short handoff). Clamped to `0..=12` client-side; streaming
 * sources only (a crossfade needs the Web Audio graph). The frontend drives the dual-deck engine.
 */
crossfade_seconds: number, 
/**
 * Parametric equalizer state.
 */
eq: EqConfig, 
/**
 * The user's saved custom EQ presets.
 */
eq_presets: Array<EqPreset>, 
/**
 * Who may see the user's profile page at all.
 */
profile_visibility: Audience, 
/**
 * Who may see the list of accounts following this user.
 */
followers_visibility: Audience, 
/**
 * Who may see the list of accounts this user follows.
 */
following_visibility: Audience, 
/**
 * Who may see this user's public playlists on their profile. Defaults to `Private`: a
 * playlist's own `PlaylistVisibility` opts it in, this only widens the *shelf*.
 */
playlists_visibility: Audience, 
/**
 * Who may see the artists this user follows.
 */
followed_artists_visibility: Audience, 
/**
 * Whether other users may follow this account without asking. Default on.
 */
open_to_follows: boolean, };
