// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The colour treatment for an entitled user's display name.
 *
 * Always a resolved, static colour: the subject may have chosen an accent that cycles or follows
 * their artwork, but a name in someone else's follower list must not animate — that is a
 * permanently painting element in a list of hundreds, which is the exact cost this app has spent
 * sessions removing. Time-varying modes collapse to their current or first colour here.
 */
export type UserFlair = { 
/**
 * A CSS colour.
 */
accent: string, 
/**
 * Two or more stops when the user chose a gradient; empty otherwise.
 */
gradient: Array<string>, };
