// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Entitlements } from "./Entitlements";
import type { ProfileBadge } from "./ProfileBadge";

/**
 * Full profile for the authenticated user.
 */
export type UserProfile = { id: string, handle: string, display_name: string, avatar_url?: string | null, created_at: bigint, 
/**
 * Whether this user has site-admin access (the admin surface). Defaults false.
 */
is_admin: boolean, 
/**
 * Whether the account's email address has been confirmed. Defaults true so legacy/partial
 * payloads don't nag verified users.
 */
email_verified: boolean, 
/**
 * Whether two-factor (TOTP) auth is enabled on the account.
 */
totp_enabled: boolean, 
/**
 * What this account may do. Served here so a feature gate anywhere in the client is a property
 * read rather than its own request — and so a gate is impossible to get wrong by inferring a
 * tier from a badge or a price.
 */
entitlements: Entitlements, 
/**
 * Badges shown beside this user's name. Identity, not billing: an account can carry a staff or
 * early-bird badge with no subscription at all.
 */
badges: Array<ProfileBadge>, };
