// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Full profile for the authenticated user.
 */
export type UserProfile = { id: string, handle: string, display_name: string, avatar_url?: string | null, created_at: bigint, 
/**
 * Whether this user has site-admin access (the admin surface). Defaults false.
 */
is_admin: boolean, 
/**
 * Whether the account's email address has been confirmed. Defaults true so legacy/partial
 * payloads don't nag verified users.
 */
email_verified: boolean, 
/**
 * Whether two-factor (TOTP) auth is enabled on the account.
 */
totp_enabled: boolean, };
