// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayoutBlock } from "./LayoutBlock";

/**
 * The blocks of one view, in order.
 */
export type ViewLayout = { blocks: Array<LayoutBlock>, };
