// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Compared } from "./Compared";
import type { DecadeBucket } from "./DecadeBucket";
import type { FingerprintReport } from "./FingerprintReport";
import type { GenreTrend } from "./GenreTrend";
import type { Period } from "./Period";
import type { TopItem } from "./TopItem";

/**
 * A listening-insights report for a user over a period.
 *
 * Computed live from the partitioned `listening_events` fact table, scoped to one user over a
 * bounded window. (This previously claimed to be served from precomputed rollups; it never was —
 * the fixed-grain rollups cannot answer an arbitrary rolling window precisely.)
 */
export type WrappedReport = { user_id: string, period: Period, 
/**
 * Inclusive start of the window (epoch millis).
 */
window_start: bigint, 
/**
 * Exclusive end of the window (epoch millis).
 */
window_end: bigint, 
/**
 * IANA timezone used to align the current and preceding windows to local midnights.
 */
timezone: string, total_plays: number, total_plays_compared: Compared, total_ms_played: bigint, total_ms_played_compared: Compared, unique_tracks: number, unique_tracks_compared: Compared, unique_artists: number, unique_artists_compared: Compared, unique_albums: number, unique_albums_compared: Compared, top_artists: Array<TopItem>, top_tracks: Array<TopItem>, top_albums: Array<TopItem>, 
/**
 * Top genres by play count. `id` is a stable hash of the genre name (genres aren't catalog
 * entities), and `image_url` is always `None`.
 */
top_genres: Array<TopItem>, 
/**
 * Continuous decade axis from the earliest dated album played through the current decade.
 */
decades: Array<DecadeBucket>, 
/**
 * Share of plays whose album release date cannot be resolved (`0.0..=1.0`).
 */
undated_release_share: number, 
/**
 * Album genres over the same local-calendar buckets used by listening charts.
 */
genre_trend: GenreTrend, fingerprint: FingerprintReport, };
